// Function to generate today's date in dd-mm-YYYY format
const getTodayDate = () => {
  const today = new Date();
  const day = String(today.getDate()).padStart(2, "0");
  const month = String(today.getMonth() + 1).padStart(2, "0");
  const year = today.getFullYear();
  return `${day}-${month}-${year}`;
};

// Function to generate yesterday's date in dd-mm-YYYY format
const getYesterdayDate = () => {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const day = String(yesterday.getDate()).padStart(2, "0");
  const month = String(yesterday.getMonth() + 1).padStart(2, "0");
  const year = yesterday.getFullYear();
  return `${day}-${month}-${year}`;
};

// Function to generate date two days ago in dd-mm-YYYY format
const getTwoDaysAgoDate = () => {
  const twoDaysAgo = new Date();
  twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
  const day = String(twoDaysAgo.getDate()).padStart(2, "0");
  const month = String(twoDaysAgo.getMonth() + 1).padStart(2, "0");
  const year = twoDaysAgo.getFullYear();
  return `${day}-${month}-${year}`;
};

export const betCrawlerData = [
  {
    id: 1,
    name: "Pinbet",
    platforms: ["Instagram"],
    followers: 12900,
    influenciadores: 3,
    posts: 585,
    lastActivity: getTodayDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "pinbet.bet",
    gateways: ["PIX"],
    cnpj: "56.638.610/0001-70",
    banks: ["Swiftpag", "Primepag"],
    creationDate: "15-03-2020",
  },
  {
    id: 2,
    name: "LuckyPlay",
    platforms: ["Instagram", "Twitter"],
    followers: 15600,
    influenciadores: 2,
    posts: 89,
    lastActivity: getTodayDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "luckyplay.bet",
    gateways: ["PIX", "Transferência"],
    cnpj: "12.345.678/0001-99",
    banks: ["Bradesco"],
    creationDate: "22-07-2020",
  },
  {
    id: 3,
    name: "GoldenBet",
    platforms: ["Facebook"],
    followers: 19300,
    influenciadores: 4,
    posts: 103,
    lastActivity: getTodayDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "goldenbet.com.br",
    gateways: ["PIX", "Boleto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["Santander", "Inter"],
    creationDate: "08-11-2020",
  },
  {
    id: 4,
    name: "WinnersBet",
    platforms: ["Instagram", "Twitter"],
    followers: 11200,
    influenciadores: 1,
    posts: 67,
    lastActivity: getTodayDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "winnersbet.io",
    gateways: ["PIX", "Crypto"],
    cnpj: "23.456.789/0001-10",
    banks: ["C6", "Inter"],
    creationDate: "05-01-2021",
  },
  {
    id: 5,
    name: "BetKing",
    platforms: ["Instagram", "Facebook", "Twitter"],
    followers: 27800,
    influenciadores: 5,
    posts: 145,
    lastActivity: getYesterdayDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "betking.com",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Itaú", "Bradesco", "Nubank"],
    creationDate: "18-04-2021",
  },
  {
    id: 6,
    name: "SambaBet",
    platforms: ["Instagram", "TikTok"],
    followers: 33500,
    influenciadores: 3,
    posts: 215,
    lastActivity: getYesterdayDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "sambabet.com.br",
    gateways: ["PIX", "Boleto", "Crypto"],
    cnpj: "34.567.890/0001-21",
    banks: ["Nubank", "Caixa"],
    creationDate: "30-08-2021",
  },
  {
    id: 7,
    name: "CarnavalGames",
    platforms: ["Facebook", "YouTube"],
    followers: 22800,
    influenciadores: 2,
    posts: 178,
    lastActivity: getYesterdayDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "carnavalgames.bet",
    gateways: ["PIX", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Banco do Brasil", "Inter"],
    creationDate: "12-12-2021",
  },
  {
    id: 8,
    name: "CopacabanaCasino",
    platforms: ["Instagram", "Twitter", "TikTok"],
    followers: 41700,
    influenciadores: 4,
    posts: 342,
    lastActivity: getYesterdayDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "copacabanacasino.com",
    gateways: ["PIX", "Boleto", "Cartão", "Crypto"],
    cnpj: "45.678.901/0001-32",
    banks: ["Itaú", "Santander", "BTG"],
    creationDate: "25-02-2022",
  },
  {
    id: 9,
    name: "IpanemaJogos",
    platforms: ["Facebook", "Instagram"],
    followers: 16400,
    influenciadores: 1,
    posts: 112,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "ipanemajogos.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["Nubank"],
    creationDate: "07-06-2022",
  },
  {
    id: 10,
    name: "FuteBet Brasil",
    platforms: ["Twitter", "Instagram"],
    followers: 38200,
    influenciadores: 4,
    posts: 289,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "futebet.com.br",
    gateways: ["PIX", "Transferência", "Crypto"],
    cnpj: "56.789.012/0001-43",
    banks: ["Bradesco", "Banco do Brasil"],
    creationDate: "19-09-2022",
  },
  {
    id: 11,
    name: "AçaíBet",
    platforms: ["Instagram", "TikTok", "YouTube"],
    followers: 29600,
    influenciadores: 3,
    posts: 198,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "acaibet.com.br",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["C6", "Inter", "Nubank"],
    creationDate: "03-01-2023",
  },
  {
    id: 12,
    name: "CaipirinhaCasino",
    platforms: ["Facebook", "Twitter"],
    followers: 18900,
    influenciadores: 2,
    posts: 143,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "caipirinhacasino.bet",
    gateways: ["PIX", "Crypto"],
    cnpj: "67.890.123/0001-54",
    banks: ["Itaú", "Santander"],
    creationDate: "16-05-2023",
  },
  {
    id: 13,
    name: "GuaranáGames",
    platforms: ["Instagram"],
    followers: 12800,
    influenciadores: 1,
    posts: 87,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "guaranagames.com",
    gateways: ["PIX"],
    cnpj: "Não identificado",
    banks: ["Nubank"],
    creationDate: "28-08-2023",
  },
  {
    id: 14,
    name: "FeijoadadaBet",
    platforms: ["TikTok", "Instagram"],
    followers: 26300,
    influenciadores: 3,
    posts: 231,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "feijoadadabet.bet",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "78.901.234/0001-65",
    banks: ["Bradesco", "Caixa"],
    creationDate: "10-11-2023",
  },
  {
    id: 15,
    name: "CaipiraBet",
    platforms: ["Facebook", "Instagram", "Twitter", "YouTube"],
    followers: 45800,
    posts: 376,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "caipirabet.com.br",
    gateways: ["PIX", "Boleto", "Cartão", "Crypto"],
    cnpj: "89.012.345/0001-76",
    banks: ["Itaú", "Bradesco", "Santander", "Inter"],
    creationDate: "14-02-2020",
  },
  // Adicionando mais 20 registros tropicalizados
  {
    id: 16,
    name: "BrasilBets",
    platforms: ["Instagram", "TikTok", "Telegram"],
    followers: 52300,
    posts: 432,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "brasilbets.com",
    gateways: ["PIX", "Boleto", "Crypto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Inter", "PicPay"],
    creationDate: "29-06-2020",
  },
  {
    id: 17,
    name: "JogaBina",
    platforms: ["Facebook", "Instagram"],
    followers: 21400,
    posts: 156,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "jogabina.bet",
    gateways: ["PIX", "Transferência"],
    cnpj: "90.123.456/0001-87",
    banks: ["Banco do Brasil", "Caixa"],
    creationDate: "11-10-2020",
  },
  {
    id: 18,
    name: "TucanoBet",
    platforms: ["Instagram", "Twitter", "YouTube"],
    followers: 34500,
    posts: 289,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "tucanobet.com.br",
    gateways: ["PIX", "Boleto", "Crypto"],
    cnpj: "Não identificado",
    banks: ["Itaú", "Bradesco", "Santander"],
    creationDate: "23-01-2021",
  },
  {
    id: 19,
    name: "PantanalGames",
    platforms: ["Facebook", "Instagram", "TikTok"],
    followers: 24700,
    posts: 178,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "pantanalgames.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "01.234.567/0001-98",
    banks: ["Nubank", "Inter"],
    creationDate: "06-05-2021",
  },
  {
    id: 20,
    name: "AmazoniaSlots",
    platforms: ["Instagram", "Telegram", "Discord"],
    followers: 39800,
    posts: 312,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "amazoniaslots.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["C6", "Nubank", "PicPay"],
    creationDate: "17-09-2021",
  },
  {
    id: 21,
    name: "CangaceiroBet",
    platforms: ["Instagram", "Facebook", "YouTube"],
    followers: 31600,
    posts: 245,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "cangaceirobet.bet",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "12.345.678/0001-09",
    banks: ["Bradesco", "Banco do Brasil"],
    creationDate: "02-12-2021",
  },
  {
    id: 22,
    name: "ChurrascoGames",
    platforms: ["Facebook", "Instagram"],
    followers: 17800,
    posts: 134,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "churrascobet.com.br",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["Itaú", "Santander"],
    creationDate: "24-03-2022",
  },
  {
    id: 23,
    name: "VaiVaiCasino",
    platforms: ["Instagram", "TikTok", "Telegram"],
    followers: 43200,
    posts: 298,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "vaivaicasino.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "23.456.789/0001-10",
    banks: ["Nubank", "C6", "Inter"],
    creationDate: "09-07-2022",
  },

  {
    id: 24,
    name: "AbacaxiBet",
    platforms: ["Instagram", "Facebook"],
    followers: 23900,
    posts: 187,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "abacaxibet.bet",
    gateways: ["PIX", "Boleto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Bradesco", "Caixa"],
    creationDate: "21-10-2022",
  },
  {
    id: 25,
    name: "JabuticabaCasino",
    platforms: ["Instagram", "Twitter", "YouTube"],
    followers: 48700,
    posts: 356,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "jabuticabacasino.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "34.567.890/0001-21",
    banks: ["Itaú", "Santander", "BTG"],
    creationDate: "04-02-2023",
  },
  {
    id: 26,
    name: "CuiaBets",
    platforms: ["Facebook", "Instagram"],
    followers: 15200,
    posts: 123,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "cuiabets.bet",
    gateways: ["PIX"],
    cnpj: "45.678.901/0001-32",
    banks: ["Nubank"],
    creationDate: "18-06-2023",
  },
  {
    id: 27,
    name: "PãoDeQueijoGames",
    platforms: ["Instagram", "TikTok"],
    followers: 28900,
    posts: 214,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "paodequejogames.com.br",
    gateways: ["PIX", "Boleto"],
    cnpj: "Não identificado",
    banks: ["Inter", "C6"],
    creationDate: "01-09-2023",
  },
  {
    id: 28,
    name: "BrigadeiroBet",
    platforms: ["Instagram", "Facebook", "Telegram"],
    followers: 36700,
    posts: 267,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "brigadeirobet.com",
    gateways: ["PIX", "Crypto", "Transferência"],
    cnpj: "56.789.012/0001-43",
    banks: ["Bradesco", "Itaú", "Nubank"],
    creationDate: "13-12-2023",
  },
  {
    id: 29,
    name: "CoxinhaBets",
    platforms: ["Facebook", "Instagram", "YouTube"],
    followers: 25600,
    posts: 198,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "coxinhabets.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "67.890.123/0001-54",
    banks: ["Banco do Brasil", "Caixa"],
    creationDate: "27-04-2020",
  },
  {
    id: 30,
    name: "PaçocaGames",
    platforms: ["Instagram", "TikTok", "Discord"],
    followers: 42100,
    posts: 287,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "pacocagames.com",
    gateways: ["PIX", "Crypto", "Cartão"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Inter", "PicPay"],
    creationDate: "20-08-2020",
  },
  {
    id: 31,
    name: "TapiocaBet",
    platforms: ["Instagram", "Facebook"],
    followers: 22400,
    posts: 165,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Médio",
    domain: "tapiocabet.bet",
    gateways: ["PIX", "Boleto"],
    cnpj: "78.901.234/0001-65",
    banks: ["Bradesco", "Itaú"],
    creationDate: "26-11-2020",
  },
  {
    id: 32,
    name: "AcarajéCasino",
    platforms: ["Instagram", "Twitter", "Telegram"],
    followers: 47300,
    posts: 324,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "acarajecasino.com.br",
    gateways: ["PIX", "Crypto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Santander", "C6", "Nubank"],
    creationDate: "09-03-2021",
  },
  {
    id: 33,
    name: "ChurrosGames",
    platforms: ["Facebook", "Instagram"],
    followers: 16800,
    influenciadores: 3,
    posts: 132,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Baixo",
    domain: "churrosgames.bet",
    gateways: ["PIX"],
    cnpj: "89.012.345/0001-76",
    banks: ["Nubank"],
    creationDate: "22-06-2021",
  },
  {
    id: 34,
    name: "PicanhaBet",
    platforms: ["Instagram", "Facebook", "YouTube"],
    followers: 33500,
    influenciadores: 3,
    posts: 254,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "picanhabet.com",
    gateways: ["PIX", "Boleto", "Cartão"],
    cnpj: "90.123.456/0001-87",
    banks: ["Itaú", "Bradesco", "Banco do Brasil"],
    creationDate: "14-10-2021",
  },
  {
    id: 35,
    name: "CatuabaCasino",
    platforms: ["Instagram", "TikTok", "Telegram"],
    followers: 38900,
    influenciadores: 3,
    posts: 278,
    lastActivity: getTwoDaysAgoDate(),
    status: "Não Regulamentada",
    risk: "Alto",
    domain: "catuabacasino.bet",
    gateways: ["PIX", "Crypto", "Transferência"],
    cnpj: "Não identificado",
    banks: ["Nubank", "Inter", "C6"],
    creationDate: "08-01-2022",
  },
];
