// Function to generate today's date in dd-mm-YYYY format
const getTodayDate = () => {
  const today = new Date();
  const day = String(today.getDate()).padStart(2, "0");
  const month = String(today.getMonth() + 1).padStart(2, "0");
  const year = today.getFullYear();
  return `${day}-${month}-${year}`;
};

// Function to generate yesterday's date in dd-mm-YYYY format
const getYesterdayDate = () => {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const day = String(yesterday.getDate()).padStart(2, "0");
  const month = String(yesterday.getMonth() + 1).padStart(2, "0");
  const year = yesterday.getFullYear();
  return `${day}-${month}-${year}`;
};

// Function to generate date two days ago in dd-mm-YYYY format
const getTwoDaysAgoDate = () => {
  const twoDaysAgo = new Date();
  twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
  const day = String(twoDaysAgo.getDate()).padStart(2, "0");
  const month = String(twoDaysAgo.getMonth() + 1).padStart(2, "0");
  const year = twoDaysAgo.getFullYear();
  return `${day}-${month}-${year}`;
};

export const betCrawlerData = [
  /* {
    id: 1,
    name: "TremBet",
    domain: "https://trembet.com",
    ip: "54.207.254.167",
    pgDomain: "https://h5.h.betcatpay.com/",
    pixUrl:
      "00020101021226880014br.gov.bcb.pix2566qrcode.microcashif.com.br/pix/bbe86e0e-c9f9-4480-af90-1282a5b17c5b5204000053039865802BR5909Vitalcred6008SaoPaulo62070503***63041122",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ivi Gateway LTDA",
    pixCnpj: "37.728.324/0001-50",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://w.trembet.com/recharge",
    registrar: "AWS",
    creationDate: "2023-05-03T14:46:52Z",
    expirationDate: "2026-05-03T14:46:52Z",
    ownerName: "Registration Private",
    registeredIn: "Identity Protection Service",
    hostingAddress: "PO Box 786, Hayes, Middlesex, UB3 9TR",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/trembetGeral.png",
    printPix: "/images/trembetPix.jpeg",
  }, */
  {
    id: 2,
    name: "0lhfh22",
    domain: "https://0lhfh22.com",
    ip: "172.64.144.232",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Elite Digital LTDA",
    pixCnpj: "63.868.900/0001-75",
    // Informações BCB
    nomeReduzido: "SANTS SCD S.A.",
    ispb: "52440987",
    cnpjBCB: "52.440.987/0001-69",
    tipoInstituicao: "Sociedade de Crédito Direto",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://0lhfh22.com/",
    registrar: "Name.com, Inc.",
    creationDate: "2025-04-05 13:33:30",
    expirationDate: "2026-04-05 13:33:30",
    ownerName: "zhao honghong",
    registeredIn: "Não encontrado",
    hostingAddress: "Vientiane,, Vientiane,, LA",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/0lhfh22Geral.png",
    printPix: "/images/0lhfh222Pix.jpg",
  },
  {
    id: 3,
    name: "58rr",
    domain: "https://58rr.top",
    ip: "104.21.96.1",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Simpay Pagamentos LTDA",
    pixReceiver: "Marketplace Pago",
    pixCnpj: "63.607.793/0001-21",
    // Informações BCB
    nomeReduzido: "SIMPAY PAGAMENTOS LTDA",
    ispb: "33982918",
    cnpjBCB: "33.982.918/0001-32",
    tipoInstituicao:
      "Instituição de Pagamento não sujeita à autorização pelo BCB",
    autorizadaBCB: "Não",
    tipoParticipacaoSPI: "Participante Indireto",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "N/A",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://58rr.top/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-08-26 07:11:45",
    expirationDate: "2026-08-26 07:11:45",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "REDACTED FOR PRIVACY",
    hostingAddress: "REDACTED FOR PRIVACY, Uttar Pradesh, IN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/58rrGeral.png",
    printPix: "/images/58rrPix.jpeg",
  },
  {
    id: 4,
    name: "dsja9",
    domain: "https://dsja9.j293-sad23-ds1.com",
    ip: "104.21.25.152",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Hyper Wallet lp LTDA",
    pixReceiver: "Bitnest Finance LTDA",
    pixCnpj: "62.410.137/0001-71",
    // Informações BCB
    nomeReduzido: "HYPER WALLET IP LTDA",
    ispb: "7136847",
    cnpjBCB: "07.136.847/0001-47",
    tipoInstituicao:
      "Instituição de Pagamento não sujeita à autorização pelo BCB",
    autorizadaBCB: "Não",
    tipoParticipacaoSPI: "Participante Indireta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "N/A",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://dsja9.j293-sad23-ds1.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-07-18 08:16:18",
    expirationDate: "2027-07-18 08:16:18",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, VN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/dsja9Geral.png",
    printPix: "/images/dsja9Pix.jpeg",
  },
  {
    id: 5,
    name: "Golden Dubai 777",
    domain: "https://ds.goldendubai777.com",
    ip: "13.227.107.63",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ivi Gateway LTDA",
    pixCnpj: "37.728.324/0001-50",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://ds.goldendubai777.com/",
    registrar: "Amazon Registrar, Inc.",
    creationDate: "2024-02-24 07:41:37",
    expirationDate: "2026-02-24 07:41:37",
    ownerName: "On behalf of goldendubai777.com owner",
    registeredIn: "Identity Protection Service",
    hostingAddress: "Hayes, Middlesex, GB",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/goldendubai777Geral.png",
    printPix: "/images/goldendubai777Pix.jpeg",
  },
  {
    id: 6,
    name: "Fortune Rabbit 777",
    domain: "https://ds.fortunerabbit777.com",
    ip: "3.162.247.114",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ivi Gateway LTDA",
    pixCnpj: "37.728.324/0001-50",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://ds.fortunerabbit777.com/",
    registrar: "Amazon Registrar, Inc.",
    creationDate: "2024-01-14 12:43:59",
    expirationDate: "2026-01-14 12:43:59",
    ownerName: "On behalf of fortunerabbit777.com owner",
    registeredIn: "Identity Protection Service",
    hostingAddress: "Hayes, Middlesex, GB",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/fortunerabbit777Geral.png",
    printPix: "/images/fortunerabbit777Pix.jpeg",
  },
  {
    id: 7,
    name: "dduu5d",
    domain: "https://dduu5d.com",
    ip: "172.64.144.140",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ivi Gateway LTDA",
    pixCnpj: "37.728.324/0001-50",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://dduu5d.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-05-27 11:27:59",
    expirationDate: "2026-05-27 11:27:59",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, KH",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/dduu5dGeral.png",
    printPix: "/images/dduu5dPix.jpeg",
  },
  {
    id: 9,
    name: "Casino VIP 11",
    domain: "https://casinovip11.com",
    ip: "172.64.153.231",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mt lp S.A.",
    pixReceiver: "Questcore",
    pixCnpj: "58.649.785/0001-08",
    // Informações BCB
    nomeReduzido: "MT IP S.A.",
    ispb: "50871921",
    cnpjBCB: "50.871.921/0001-06",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Participante Direto",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://casinovip11.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2023-08-11 13:52:17",
    expirationDate: "2026-08-11 13:52:17",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/casinovip11Geral.png",
    printPix: "/images/casinovip11Pix.jpeg",
  },
  {
    id: 10,
    name: "j0831vf",
    domain: "http://j0831vf.com",
    ip: "172.64.144.191",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Tycoon Technology lip S.A",
    pixReceiver: "Koreabet",
    pixCnpj: "57.927.308/0001-02",
    // Informações BCB
    nomeReduzido: "TYCOON TECHNOLOGY IIP S.A",
    ispb: "26615279",
    cnpjBCB: "26.615.279/0001-01",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Participante Direto",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://j0831vf.com/",
    registrar: "Name.com, Inc.",
    creationDate: "2024-10-11 14:59:31",
    expirationDate: "2027-10-11 14:59:31",
    ownerName: "wang haohao",
    registeredIn: "Não encontrado",
    hostingAddress: "Brasil, Vientiane,, LA",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/j0831vfGeral.png",
    printPix: "/images/j0831vfPix.jpeg",
  },
  {
    id: 11,
    name: "Independência 777",
    domain: "http://m.independencia777lg.com",
    ip: "172.67.69.244",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ivi Gateway LTDA",
    pixCnpj: "37.728.324/0001-50",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "http://m.independencia777lg.com/",
    registrar: "Cloudflare, Inc.",
    creationDate: "2024-08-21 03:46:13",
    expirationDate: "2026-08-21 03:46:13",
    ownerName: "DATA REDACTED",
    registeredIn: "DATA REDACTED",
    hostingAddress: "DATA REDACTED, q, AL",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/independencia777Geral.png",
    printPix: "/images/independencia777Pix.jpeg",
  },
  {
    id: 12,
    name: "Ubebet7",
    domain: "http://ubebet7.com",
    ip: "76.76.21.21",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Fitbank lp",
    pixReceiver: "Paygate",
    pixCnpj: "56.109.743/0001-59",
    // Informações BCB
    nomeReduzido: "FITBANK IP",
    ispb: "13203354",
    cnpjBCB: "13.203.354/0001-85",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Participante Direto",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://ubebet7.com/",
    registrar: "Squarespace Domains LLC",
    creationDate: "2025-01-26 15:30:43",
    expirationDate: "2026-01-26 15:30:43",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "Não encontrado",
    hostingAddress: "REDACTED FOR PRIVACY, PA, BR",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/ubebet7Geral.png",
    printPix: "/images/ubebet7Pix.jpeg",
  },
  {
    id: 13,
    name: "44uj",
    domain: "https://44uj.vip",
    ip: "104.18.2.87",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ivi Gateway LTDA",
    pixCnpj: "37.728.324/0001-50",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://44uj.vip/",
    registrar: "DYNADOT LLC",
    creationDate: "2025-07-29 07:40:47",
    expirationDate: "2026-07-29 07:40:47",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "Super Privacy Service LTD c/o Dynadot",
    hostingAddress: "REDACTED FOR PRIVACY, California, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/44ujGeral.png",
    printPix: "/images/44ujPix.jpeg",
  },
  {
    id: 15,
    name: "6qq9",
    domain: "https://6qq9.com",
    ip: "104.18.26.112",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ajc Gateway LTDA",
    pixCnpj: "63.868.900/0001-75",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://6qq9.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-07-25 13:38:03",
    expirationDate: "2026-07-25 13:38:03",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/6qq9Geral.png",
    printPix: "/images/6qq9Pix.jpeg",
  },
  {
    id: 16,
    name: "7622",
    domain: "https://7622.com",
    ip: "104.21.32.1",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Sants Scd S.A",
    pixReceiver: "Digital Core LTDA",
    pixCnpj: "64.259.855/0001-14",
    // Informações BCB
    nomeReduzido: "SANTS SCD S.A.",
    ispb: "52440987",
    cnpjBCB: "52.440.987/0001-69",
    tipoInstituicao: "Sociedade de Crédito Direto",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://7622a.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2004-01-21 08:36:24",
    expirationDate: "2027-01-21 08:36:24",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/7622Geral.png",
    printPix: "/images/7622Pix.jpeg",
  },
  {
    id: 17,
    name: "8385ma",
    domain: "https://8385ma.com",
    ip: "104.18.36.141",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Mw lp LTDA",
    pixReceiver: "Ajc Gateway LTDA",
    pixCnpj: "63.868.900/0001-75",
    // Informações BCB
    nomeReduzido: "MW IP LTDA.",
    ispb: "53822116",
    cnpjBCB: "53.822.116/0001-72",
    tipoInstituicao: "Instituição de Pagamento",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Direta",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://8385ma.com/",
    registrar: "Name.com, Inc.",
    creationDate: "2025-07-16 03:46:08",
    expirationDate: "2030-07-16 03:46:08",
    ownerName: "ming li",
    registeredIn: "jpz888",
    hostingAddress: "xigang, xigang, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/8385maGeral.png",
    printPix: "/images/8385maPix.jpeg",
  },
  {
    id: 18,
    name: "889bet02",
    domain: "https://889bet02.com",
    ip: "104.21.41.178",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "A55 Scd S.A.",
    pixReceiver:
      "Koreabet Tecnologia e Administradora de Apostas Esportivas LTDA",
    pixCnpj: "57.927.308/0001-02",
    // Informações BCB
    nomeReduzido: "A55 SCD S.A.",
    ispb: "48756121",
    cnpjBCB: "48.756.121/0001-94",
    tipoInstituicao: "Sociedade de Crédito Direto",
    autorizadaBCB: "Sim",
    tipoParticipacaoSPI: "Participante Direto",
    tipoParticipacaoPix: "Facultativa",
    modalidadeParticipacaoPix: "Provedor de Conta Transacional",
    iniciacaoTransacao: "Não",
    facilitadorSaqueTroco: "Não",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://889bet02.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-07-13 14:44:43",
    expirationDate: "2026-07-13 14:44:43",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, IN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/images/889bet02Geral.png",
    printPix: "/images/889bet02Pix.jpeg",
  },
];
