// Function to generate today's date in dd-mm-YYYY format
const getTodayDate = () => {
  const today = new Date();
  const day = String(today.getDate()).padStart(2, "0");
  const month = String(today.getMonth() + 1).padStart(2, "0");
  const year = today.getFullYear();
  return `${day}-${month}-${year}`;
};

// Function to generate yesterday's date in dd-mm-YYYY format
const getYesterdayDate = () => {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const day = String(yesterday.getDate()).padStart(2, "0");
  const month = String(yesterday.getMonth() + 1).padStart(2, "0");
  const year = yesterday.getFullYear();
  return `${day}-${month}-${year}`;
};

// Function to generate date two days ago in dd-mm-YYYY format
const getTwoDaysAgoDate = () => {
  const twoDaysAgo = new Date();
  twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
  const day = String(twoDaysAgo.getDate()).padStart(2, "0");
  const month = String(twoDaysAgo.getMonth() + 1).padStart(2, "0");
  const year = twoDaysAgo.getFullYear();
  return `${day}-${month}-${year}`;
};

export const betCrawlerData = [
  {
    id: 1,
    name: "TremBet",
    domain: "https://trembet.com",
    ip: "54.207.254.167",
    pgDomain: "https://h5.h.betcatpay.com/",
    pixUrl:
      "00020101021226880014br.gov.bcb.pix2566qrcode.microcashif.com.br/pix/bbe86e0e-c9f9-4480-af90-1282a5b17c5b5204000053039865802BR5909Vitalcred6008SaoPaulo62070503***63041122",
    cnpj: "Não encontrado",
    pgGateway:
      "MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA",
    pixReceiver: "Evan",
    pixCnpj: "***.118.218-**",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://w.trembet.com/recharge",
    registrar: "AWS",
    creationDate: "2023-05-03T14:46:52Z",
    expirationDate: "2026-05-03T14:46:52Z",
    ownerName: "Registration Private",
    registeredIn: "Identity Protection Service",
    hostingAddress: "PO Box 786, Hayes, Middlesex, UB3 9TR",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/trembetGeral.png",
    printPix: "/src/assets/trembetPix.jpg",
  },
  {
    id: 2,
    name: "0lhfh22",
    domain: "https://0lhfh22.com",
    ip: "172.64.144.232",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Saq",
    pixReceiver: "Lpx Gestao de Negocios LTDA",
    pixCnpj: "61.277.090/0001-42",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://0lhfh22.com/",
    registrar: "Name.com, Inc.",
    creationDate: "2025-04-05 13:33:30",
    expirationDate: "2026-04-05 13:33:30",
    ownerName: "zhao honghong",
    registeredIn: "Não encontrado",
    hostingAddress: "Vientiane,, Vientiane,, LA",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/0lhfh22Geral.png",
    printPix: "/src/assets/0lhfh22Pix.jpg",
  },
  {
    id: 3,
    name: "58rr",
    domain: "https://58rr.top",
    ip: "104.21.96.1",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcans Scmedd LTDA",
    pixReceiver: "Podium Clube Tecnologia LTDA",
    pixCnpj: "55.334.955/0001-77",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://58rr.top/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-08-26 07:11:45",
    expirationDate: "2026-08-26 07:11:45",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "REDACTED FOR PRIVACY",
    hostingAddress: "REDACTED FOR PRIVACY, Uttar Pradesh, IN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/58rrGeral.png",
    printPix: "/src/assets/58rrPix.jpg",
  },
  {
    id: 4,
    name: "dsja9",
    domain: "https://dsja9.j293-sad23-ds1.com",
    ip: "104.21.25.152",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Sants Scd S.A.",
    pixReceiver: "Probet Tecnologia LTDA",
    pixCnpj: "61.747.555/0001-96",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://dsja9.j293-sad23-ds1.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-07-18 08:16:18",
    expirationDate: "2027-07-18 08:16:18",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, VN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/dsja9Geral.png",
    printPix: "/src/assets/dsja9Pix.jpg",
  },
  {
    id: 5,
    name: "Golden Dubai 777",
    domain: "https://ds.goldendubai777.com",
    ip: "13.227.107.63",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcash Scmepp LTDA",
    pixReceiver: "Ds Solucoes LTDA",
    pixCnpj: "57.633.340/0001-77",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://ds.goldendubai777.com/",
    registrar: "Amazon Registrar, Inc.",
    creationDate: "2024-02-24 07:41:37",
    expirationDate: "2026-02-24 07:41:37",
    ownerName: "On behalf of goldendubai777.com owner",
    registeredIn: "Identity Protection Service",
    hostingAddress: "Hayes, Middlesex, GB",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/goldendubai777Geral.png",
    printPix: "/src/assets/goldendubai777Pix.jpg",
  },
  {
    id: 6,
    name: "Fortune Rabbit 777",
    domain: "https://ds.fortunerabbit777.com",
    ip: "3.162.247.114",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcash Scmepp LTDA",
    pixReceiver: "Ds Solucoes LTDA",
    pixCnpj: "57.633.340/0001-77",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://ds.fortunerabbit777.com/",
    registrar: "Amazon Registrar, Inc.",
    creationDate: "2024-01-14 12:43:59",
    expirationDate: "2026-01-14 12:43:59",
    ownerName: "On behalf of fortunerabbit777.com owner",
    registeredIn: "Identity Protection Service",
    hostingAddress: "Hayes, Middlesex, GB",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/fortunerabbit777Geral.png",
    printPix: "/src/assets/fortunerabbit777Pix.jpg",
  },
  {
    id: 7,
    name: "dduu5d",
    domain: "https://dduu5d.com",
    ip: "172.64.144.140",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Sants Scd S.A.",
    pixReceiver: "Hc Infraestrutura de Pagamentos LTDA",
    pixCnpj: "45.114.753/0001-66",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://dduu5d.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-05-27 11:27:59",
    expirationDate: "2026-05-27 11:27:59",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, KH",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/dduu5dGeral.png",
    printPix: "/src/assets/dduu5dPix.jpg",
  },
  {
    id: 8,
    name: "d777",
    domain: "https://d777.game",
    ip: "104.18.39.172",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Picpay",
    pixReceiver: "Pay 4 Play Servicos LTDA",
    pixCnpj: "02.825.531/0001-49",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://d777.game/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-06-20 13:05:50",
    expirationDate: "2026-06-20 23:59:59",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/d777Geral.png",
    printPix: "/src/assets/d777Pix.jpg",
  },
  {
    id: 9,
    name: "Casino VIP 11",
    domain: "https://casinovip11.com",
    ip: "172.64.153.231",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Ponto Info",
    pixReceiver: "Probet Tecnologia LTDA",
    pixCnpj: "61.747.555/0001-96",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://casinovip11.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2023-08-11 13:52:17",
    expirationDate: "2026-08-11 13:52:17",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/casinovip11Geral.png",
    printPix: "/src/assets/casinovip11Pix.jpg",
  },
  {
    id: 10,
    name: "j0831vf",
    domain: "http://j0831vf.com",
    ip: "172.64.144.191",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Sants Scd S.A",
    pixReceiver: "Hc Infraestrutura de Pagamentos LTDA",
    pixCnpj: "45.114.753/0001-66",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://j0831vf.com/",
    registrar: "Name.com, Inc.",
    creationDate: "2024-10-11 14:59:31",
    expirationDate: "2027-10-11 14:59:31",
    ownerName: "wang haohao",
    registeredIn: "Não encontrado",
    hostingAddress: "Brasil, Vientiane,, LA",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/j0831vfGeral.png",
    printPix: "/src/assets/j0831vfPix.jpg",
  },
  {
    id: 11,
    name: "Independência 777",
    domain: "http://m.independencia777lg.com",
    ip: "172.67.69.244",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcash Scmedd LTDA",
    pixReceiver: "Ds Solucoes LTDA",
    pixCnpj: "57.633.340/0001-77",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "http://m.independencia777lg.com/",
    registrar: "Cloudflare, Inc.",
    creationDate: "2024-08-21 03:46:13",
    expirationDate: "2026-08-21 03:46:13",
    ownerName: "DATA REDACTED",
    registeredIn: "DATA REDACTED",
    hostingAddress: "DATA REDACTED, q, AL",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/independencia777Geral.png",
    printPix: "/src/assets/independencia777Pix.jpg",
  },
  {
    id: 12,
    name: "Ubebet7",
    domain: "http://ubebet7.com",
    ip: "76.76.21.21",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Não encontrado",
    pixReceiver: "Não encontrado",
    pixCnpj: "Não encontrado",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://ubebet7.com/",
    registrar: "Squarespace Domains LLC",
    creationDate: "2025-01-26 15:30:43",
    expirationDate: "2026-01-26 15:30:43",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "Não encontrado",
    hostingAddress: "REDACTED FOR PRIVACY, PA, BR",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/ubebet7Geral.png",
    printPix: "/src/assets/ubebet7Pix.jpg",
  },
  {
    id: 13,
    name: "44uj",
    domain: "https://44uj.vip",
    ip: "104.18.2.87",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Sants Scd S.A.",
    pixReceiver: "Probet Tecnologia LTDA",
    pixCnpj: "61.747.555/0001-69",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://44uj.vip/",
    registrar: "DYNADOT LLC",
    creationDate: "2025-07-29 07:40:47",
    expirationDate: "2026-07-29 07:40:47",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "Super Privacy Service LTD c/o Dynadot",
    hostingAddress: "REDACTED FOR PRIVACY, California, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/44ujGeral.png",
    printPix: "/src/assets/44ujPix.jpg",
  },
  {
    id: 14,
    name: "6kgame",
    domain: "http://6kgame.com",
    ip: "47.109.195.222",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Não encontrado",
    pixReceiver: "Não encontrado",
    pixCnpj: "Não encontrado",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "http://6kgame.com/",
    registrar: "Alibaba Cloud Computing (Beijing) Co., Ltd.",
    creationDate: "2014-03-20 07:41:38",
    expirationDate: "2026-03-20 07:41:38",
    ownerName: "Não encontrado",
    registeredIn: "Não encontrado",
    hostingAddress: "si chuan, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/6kgameGeral.png",
    printPix: "/src/assets/6kgamePix.jpg",
  },
  {
    id: 15,
    name: "6qq9",
    domain: "https://6qq9.com",
    ip: "104.18.26.112",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Prototype Ip S.A.",
    pixReceiver: "Novabet",
    pixCnpj: "61.962.430/0001-89",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://6qq9.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-07-25 13:38:03",
    expirationDate: "2026-07-25 13:38:03",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/6qq9Geral.png",
    printPix: "/src/assets/6qq9Pix.jpg",
  },
  {
    id: 16,
    name: "7622",
    domain: "https://7622.com",
    ip: "104.21.32.1",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Saq",
    pixReceiver: "Jogo Infinito Tecnologia Ltd LTDA",
    pixCnpj: "59.289.045/0001-70",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://7622a.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2004-01-21 08:36:24",
    expirationDate: "2027-01-21 08:36:24",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/7622Geral.png",
    printPix: "/src/assets/7622Pix.jpg",
  },
  {
    id: 17,
    name: "8385ma",
    domain: "https://8385ma.com",
    ip: "104.18.36.141",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Saq",
    pixReceiver: "Sirius Pay LTDA",
    pixCnpj: "53.348.968/0001-70",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://8385ma.com/",
    registrar: "Name.com, Inc.",
    creationDate: "2025-07-16 03:46:08",
    expirationDate: "2030-07-16 03:46:08",
    ownerName: "ming li",
    registeredIn: "jpz888",
    hostingAddress: "xigang, xigang, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/8385maGeral.png",
    printPix: "/src/assets/8385maPix.jpg",
  },
  {
    id: 18,
    name: "889bet02",
    domain: "https://889bet02.com",
    ip: "104.21.41.178",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Picpay",
    pixReceiver: "Pay 4 Ply Servicos LTDA",
    pixCnpj: "02.825.531/0001-49",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://889bet02.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-07-13 14:44:43",
    expirationDate: "2026-07-13 14:44:43",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, IN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/889bet02Geral.png",
    printPix: "/src/assets/889bet02Pix.jpg",
  },
  {
    id: 19,
    name: "92567-mp",
    domain: "https://92567-mp.top",
    ip: "178.253.37.185",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Saq",
    pixReceiver: "Jogo Infinito Tecnologia Ltd LTDA",
    pixCnpj: "59.289.045/00001-70",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://92567-mp.top/en",
    registrar: "URL Solutions Inc.",
    creationDate: "2025-02-21 11:11:35",
    expirationDate: "2026-02-21 11:11:35",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "REDACTED FOR PRIVACY",
    hostingAddress: "REDACTED FOR PRIVACY, NA, PA",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/92567-mpGeral.png",
    printPix: "/src/assets/92567-mpPix.jpg",
  },
  {
    id: 20,
    name: "992bet",
    domain: "https://992bet.org",
    ip: "18.155.21.35",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Saq",
    pixReceiver: "Jogo Infinito Tecnologia Ltd LTDA",
    pixCnpj: "59.289.045/00001-70",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://992bet.org/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2024-07-01 13:52:28",
    expirationDate: "2026-07-01 13:52:28",
    ownerName: "REDACTED",
    registeredIn: "wm zong he chao shi",
    hostingAddress: "REDACTED, ma ni la, PH",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/992betGeral.png",
    printPix: "/src/assets/992betPix.jpg",
  },
  {
    id: 21,
    name: "bbrbet",
    domain: "https://bbrbet.com",
    ip: "104.21.2.241",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcash Scmepp LTDA.",
    pixReceiver: "Vitalcred Meios de Pagamento S A",
    pixCnpj: "08.022.117/0001-88",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://www.bbr596.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2022-10-27 02:40:58",
    expirationDate: "2025-10-27 02:40:58",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/bbrbetGeral.png",
    printPix: "/src/assets/bbrbetPix.jpg",
  },
  {
    id: 22,
    name: "bethhh",
    domain: "https://bethhh.com",
    ip: "128.14.249.220",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Ponto Info",
    pixReceiver: "Probet Tecnologia LTDA",
    pixCnpj: "61.747.555/0001-96",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://bethhh.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2014-12-29 07:12:36",
    expirationDate: "2025-12-29 07:12:36",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/bethhhGeral.png",
    printPix: "/src/assets/bethhhPix.jpg",
  },
  {
    id: 23,
    name: "betweb",
    domain: "https://betweb.cc",
    ip: "172.64.148.84",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcash Scmepp LTDA.",
    pixReceiver: "Vitalcred Meios de Pagamento S A",
    pixCnpj: "08.022.117/0001-88",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://betweb.cc/",
    registrar: "DYNADOT LLC",
    creationDate: "2023-07-05 08:41:48",
    expirationDate: "2027-07-05 08:41:48",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "Super Privacy Service LTD c/o Dynadot",
    hostingAddress: "San Mateo, California, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/betwebGeral.png",
    printPix: "/src/assets/betwebPix.jpg",
  },
  {
    id: 24,
    name: "bralucky",
    domain: "https://bralucky.com",
    ip: "172.67.128.254",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Prototype Ip S.A.",
    pixReceiver: "Lr Servicos Empresariais",
    pixCnpj: "54.343.501/0001-08",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://www.bralucky005.com/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2023-04-09 02:54:04",
    expirationDate: "2026-04-09 02:54:04",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/braluckyGeral.png",
    printPix: "/src/assets/braluckyPix.jpg",
  },
  {
    id: 25,
    name: "Jili707",
    domain: "https://Jili707.com",
    ip: "104.21.112.1",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Prototype Ip S.A.",
    pixReceiver: "Novabet",
    pixCnpj: "61.962.430/0001-89",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://www.jili707.com/",
    registrar: "Gandi SAS",
    creationDate: "2023-03-22 05:14:03",
    expirationDate: "2028-03-22 05:14:03",
    ownerName: "REDACTED FOR PRIVACY",
    registeredIn: "Não encontrado",
    hostingAddress: "REDACTED FOR PRIVACY, CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/Jili707Geral.png",
    printPix: "/src/assets/Jili707Pix.jpg",
  },
  {
    id: 26,
    name: "acerteibet",
    domain: "https://acerteibet.com",
    ip: "104.21.60.40",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "56472610028848",
    pgGateway: "Prototype Ip S.A.",
    pixReceiver: "Pagamento Seguro Horsepay",
    pixCnpj: "62.134.421/0001-62",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://www.acerteibet.com/",
    registrar: "NAMECHEAP INC",
    creationDate: "2023-05-02 20:02:12",
    expirationDate: "2026-05-02 20:02:12",
    ownerName: "Redacted for Privacy",
    registeredIn: "Privacy service provided by Withheld for Privacy ehf",
    hostingAddress: "Reykjavik, Capital Region, IS",
    ownerCnpj: "56472610028848",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/acerteibetGeral.png",
    printPix: "/src/assets/acerteibetPix.jpg",
  },
  {
    id: 27,
    name: "w1-pecanpg",
    domain: "http://w1-pecanpg.com",
    ip: "104.18.21.171",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Prototype Ip S.A",
    pixReceiver: "Novabet",
    pixCnpj: "61.962.430/0001-89",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://w1-pecanpg.com/",
    registrar: "Gname.com Pte. Ltd.",
    creationDate: "2025-08-14 01:41:33",
    expirationDate: "2026-08-14 01:41:33",
    ownerName: "Redacted for privacy",
    registeredIn: "Redacted for privacy",
    hostingAddress: "Redacted for privacy, Redacted for privacy, HK,CN",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/w1-pecanpgGeral.png",
    printPix: "/src/assets/w1-pecanpgPix.jpg",
  },
  {
    id: 28,
    name: "waybet",
    domain: "http://waybet.com",
    ip: "104.18.15.65",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "Microcash Scmedd LTDA",
    pixReceiver: "Vitalcred Meios de Pagamento S.A",
    pixCnpj: "08.022.117/0001-88",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "https://waybet.com/fapage/",
    registrar: "GoDaddy.com, LLC",
    creationDate: "2006-05-07 14:47:21",
    expirationDate: "2026-05-07 14:47:21",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/waybetGeral.png",
    printPix: "/src/assets/waybetPix.jpg",
  },
  {
    id: 29,
    name: "zzzz",
    domain: "http://zzzz.com",
    ip: "104.18.39.172",
    pgDomain: "Não encontrado",
    pixUrl: "Não encontrado",
    cnpj: "Não encontrado",
    pgGateway: "saq",
    pixReceiver: "Prime Solucoes Estrategicas LTDA",
    pixCnpj: "60.619.690/0001-93",
    geolocation: "Desconhecida, Desconhecida, Desconhecido",
    finalUrl: "http://zzzz.com",
    registrar: "GoDaddy.com, LLC",
    creationDate: "1996-04-13 04:00:00",
    expirationDate: "2031-04-14 04:00:00",
    ownerName: "Registration Private",
    registeredIn: "Domains By Proxy, LLC",
    hostingAddress: "Tempe, Arizona, US",
    ownerCnpj: "Não encontrado",
    status: "Não Regulamentada",
    risk: "Alto",
    printGeral: "/src/assets/zzzzGeral.png",
    printPix: "/src/assets/zzzzPix.jpg",
  },
];
