export const registerBet = [
  {
    empresa: "BetMax Brasil",
    redesSociais: {
      instagram: "@betmaxbr",
      x: "@betmax_brasil",
      discord: "discord.gg/betmax",
      telegram: "@betmaxbr",
      facebook: "fb.com/betmaxbr",
    },
    termosProibidos: [
      "ganhe dinheiro fácil",
      "aposta garantida",
      "renda extra certa",
    ],
    agendamentosSemanais: 2,
  },
  {
    empresa: "ApostaVip",
    redesSociais: {
      instagram: "@apostavip",
      x: "@vip_apostas",
      discord: "discord.gg/apostavip",
      telegram: "@apostavip",
      facebook: "fb.com/apostavip",
    },
    termosProibidos: [
      "vitória assegurada",
      "lucro sem risco",
      "certeza de ganhar",
    ],
    agendamentosSemanais: 3,
  },
  {
    empresa: "TurboBets",
    redesSociais: {
      instagram: "@turbobets",
      x: "@turbobets_ofc",
      discord: "discord.gg/turbobets",
      telegram: "@turbobets",
      facebook: "fb.com/turbobets",
    },
    termosProibidos: [
      "dinheiro fácil",
      "renda fixa com apostas",
      "aposta certeira",
    ],
    agendamentosSemanais: 1,
  },
  {
    empresa: "MegaOddz",
    redesSociais: {
      instagram: "@megaoddz",
      x: "@oddz_mega",
      discord: "discord.gg/megaoddz",
      telegram: "@megaoddzbr",
      facebook: "fb.com/megaoddz",
    },
    termosProibidos: ["lucro garantido", "dinheiro rápido", "sem perder"],
    agendamentosSemanais: 3,
  },
  {
    empresa: "PlayBetNow",
    redesSociais: {
      instagram: "@playbetnow",
      x: "@playbet_oficial",
      discord: "discord.gg/playbetnow",
      telegram: "@playbetnow",
      facebook: "fb.com/playbetnow",
    },
    termosProibidos: [
      "ganhar sem risco",
      "100% de retorno",
      "investimento seguro",
    ],
    agendamentosSemanais: 2,
  },
  {
    empresa: "LuckZone",
    redesSociais: {
      instagram: "@luckzonebr",
      x: "@luckzone_bets",
      discord: "discord.gg/luckzone",
      telegram: "@luckzone",
      facebook: "fb.com/luckzonebets",
    },
    termosProibidos: [
      "renda garantida",
      "faça dinheiro agora",
      "certeza absoluta",
    ],
    agendamentosSemanais: 2,
  },
  {
    empresa: "TopAposta360",
    redesSociais: {
      instagram: "@topaposta360",
      x: "@top_aposta360",
      discord: "discord.gg/topaposta",
      telegram: "@topaposta360",
      facebook: "fb.com/topaposta360",
    },
    termosProibidos: ["aposta infalível", "retorno certo", "ganhos imediatos"],
    agendamentosSemanais: 1,
  },
  {
    empresa: "WinMaster Bet",
    redesSociais: {
      instagram: "@winmasterbet",
      x: "@winmaster_ofc",
      discord: "discord.gg/winmaster",
      telegram: "@winmasterbet",
      facebook: "fb.com/winmasterbet",
    },
    termosProibidos: [
      "fique rico apostando",
      "lucro sem esforço",
      "ganhar sempre",
    ],
    agendamentosSemanais: 3,
  },
  {
    empresa: "BetOnFire",
    redesSociais: {
      instagram: "@betonfire",
      x: "@betonfirebr",
      discord: "discord.gg/betonfire",
      telegram: "@betonfire",
      facebook: "fb.com/betonfire",
    },
    termosProibidos: ["100% lucro", "sem chance de perda", "certeza de lucro"],
    agendamentosSemanais: 2,
  },
  {
    empresa: "GoldBets Club",
    redesSociais: {
      instagram: "@goldbetsclub",
      x: "@goldbets_club",
      discord: "discord.gg/goldbets",
      telegram: "@goldbetsclub",
      facebook: "fb.com/goldbetsclub",
    },
    termosProibidos: ["invista e ganhe", "segurança garantida", "ganhos fixos"],
    agendamentosSemanais: 1,
  },
];

export const scrapingResults = [
  // BetMax Brasil
  {
    empresa: "BetMax Brasil",
    perfil: "@betmaxbr",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-15 14:30:00",
    textoPostagem:
      "Venha fazer parte da BetMax e descubra como ter ganhos incríveis! Nossa plataforma oferece as melhores odds do mercado. #apostas #futebol #ganhe",
    linkPostagem: "https://instagram.com/p/betmaxbr12345",
    sentimento: "Positivo",
    palavrasChaveEncontradas: ["ganhe dinheiro fácil"],
    violacaoTermos: true,
  },
  {
    empresa: "BetMax Brasil",
    perfil: "@betmax_brasil",
    redeSocial: "X",
    dataPostagem: "2024-06-12 09:15:00",
    textoPostagem:
      "Aposte hoje no jogo do Flamengo e tenha uma aposta garantida! Nossos especialistas analisaram todas as estatísticas. #BetMax #ApostaEsportiva",
    linkPostagem: "https://x.com/betmax_brasil/status/123456789",
    sentimento: "Neutro",
    palavrasChaveEncontradas: ["aposta garantida"],
    violacaoTermos: true,
  },

  // ApostaVip
  {
    empresa: "ApostaVip",
    perfil: "@apostavip",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-10 18:45:00",
    textoPostagem:
      "Novo bônus de boas-vindas! Cadastre-se hoje e receba até R$200 para começar suas apostas. Termos e condições se aplicam. #ApostaVip #Bônus",
    linkPostagem: "https://instagram.com/p/apostavip54321",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },
  {
    empresa: "ApostaVip",
    perfil: "@vip_apostas",
    redeSocial: "X",
    dataPostagem: "2024-06-08 21:30:00",
    textoPostagem:
      "Aposte com a ApostaVip e tenha vitória assegurada nos jogos de hoje! Nossas dicas são baseadas em análises profundas. #ApostaVip #Futebol",
    linkPostagem: "https://x.com/vip_apostas/status/987654321",
    sentimento: "Positivo",
    palavrasChaveEncontradas: ["vitória assegurada"],
    violacaoTermos: true,
  },

  // TurboBets
  {
    empresa: "TurboBets",
    perfil: "@turbobets",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-14 12:20:00",
    textoPostagem:
      "Quer ganhar uma renda extra? A TurboBets te ensina como fazer dinheiro fácil com apostas esportivas! Clique no link da bio. #TurboBets #Apostas",
    linkPostagem: "https://instagram.com/p/turbobets67890",
    sentimento: "Positivo",
    palavrasChaveEncontradas: ["dinheiro fácil"],
    violacaoTermos: true,
  },
  {
    empresa: "TurboBets",
    perfil: "@turbobets_ofc",
    redeSocial: "X",
    dataPostagem: "2024-06-11 16:40:00",
    textoPostagem:
      "Novos mercados disponíveis para apostas na Champions League! Confira nossas odds competitivas e faça suas apostas. #TurboBets #ChampionsLeague",
    linkPostagem: "https://x.com/turbobets_ofc/status/135792468",
    sentimento: "Neutro",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },

  // MegaOddz
  {
    empresa: "MegaOddz",
    perfil: "@megaoddz",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-13 10:05:00",
    textoPostagem:
      "Aposte na MegaOddz e tenha lucro garantido! Nossos algoritmos selecionam as melhores oportunidades para você não perder. #MegaOddz #Lucro",
    linkPostagem: "https://instagram.com/p/megaoddz24680",
    sentimento: "Positivo",
    palavrasChaveEncontradas: ["lucro garantido", "sem perder"],
    violacaoTermos: true,
  },
  {
    empresa: "MegaOddz",
    perfil: "@oddz_mega",
    redeSocial: "X",
    dataPostagem: "2024-06-09 14:15:00",
    textoPostagem:
      "Dicas quentes para o fim de semana! Aposte agora e garanta seu dinheiro rápido com a MegaOddz! #Apostas #DicasQuentes",
    linkPostagem: "https://x.com/oddz_mega/status/246813579",
    sentimento: "Positivo",
    palavrasChaveEncontradas: ["dinheiro rápido"],
    violacaoTermos: true,
  },

  // PlayBetNow
  {
    empresa: "PlayBetNow",
    perfil: "@playbetnow",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-07 19:30:00",
    textoPostagem:
      "Novo cassino ao vivo disponível! Jogue agora e divirta-se com nossos dealers profissionais. Bônus especial para novos jogadores. #PlayBetNow #Casino",
    linkPostagem: "https://instagram.com/p/playbetnow13579",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },
  {
    empresa: "PlayBetNow",
    perfil: "@playbet_oficial",
    redeSocial: "X",
    dataPostagem: "2024-06-05 11:45:00",
    textoPostagem:
      "Faça seu investimento seguro na PlayBetNow! Garantimos 100% de retorno nas suas primeiras apostas. Ganhar sem risco nunca foi tão fácil! #PlayBetNow",
    linkPostagem: "https://x.com/playbet_oficial/status/975318642",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [
      "ganhar sem risco",
      "100% de retorno",
      "investimento seguro",
    ],
    violacaoTermos: true,
  },

  // LuckZone
  {
    empresa: "LuckZone",
    perfil: "@luckzonebr",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-16 08:20:00",
    textoPostagem:
      "Quer uma renda garantida? A LuckZone tem o sistema perfeito para você! Faça dinheiro agora mesmo com nossas dicas exclusivas. #LuckZone #Apostas",
    linkPostagem: "https://instagram.com/p/luckzonebr86420",
    sentimento: "Positivo",
    palavrasChaveEncontradas: ["renda garantida", "faça dinheiro agora"],
    violacaoTermos: true,
  },
  {
    empresa: "LuckZone",
    perfil: "@luckzone_bets",
    redeSocial: "X",
    dataPostagem: "2024-06-14 15:10:00",
    textoPostagem:
      "Promoção especial para o campeonato brasileiro! Aposte com a LuckZone e receba odds aumentadas. Consulte regulamento no site. #LuckZone #Brasileirão",
    linkPostagem: "https://x.com/luckzone_bets/status/864209753",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },

  // TopAposta360
  {
    empresa: "TopAposta360",
    perfil: "@topaposta360",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-12 17:25:00",
    textoPostagem:
      "Nossa aposta infalível para hoje! Siga nossas dicas e tenha retorno certo em seus investimentos. Ganhos imediatos garantidos! #TopAposta360",
    linkPostagem: "https://instagram.com/p/topaposta360-97531",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [
      "aposta infalível",
      "retorno certo",
      "ganhos imediatos",
    ],
    violacaoTermos: true,
  },
  {
    empresa: "TopAposta360",
    perfil: "@top_aposta360",
    redeSocial: "X",
    dataPostagem: "2024-06-10 13:40:00",
    textoPostagem:
      "Novo app disponível! Baixe agora a TopAposta360 e tenha a melhor experiência de apostas na palma da sua mão. #TopAposta360 #NovoApp",
    linkPostagem: "https://x.com/top_aposta360/status/753197531",
    sentimento: "Neutro",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },

  // WinMaster Bet
  {
    empresa: "WinMaster Bet",
    perfil: "@winmasterbet",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-08 09:50:00",
    textoPostagem:
      "Fique rico apostando com a WinMaster! Nosso sistema garante que você vai ganhar sempre! Lucro sem esforço para todos os apostadores. #WinMaster",
    linkPostagem: "https://instagram.com/p/winmasterbet-24680",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [
      "fique rico apostando",
      "lucro sem esforço",
      "ganhar sempre",
    ],
    violacaoTermos: true,
  },
  {
    empresa: "WinMaster Bet",
    perfil: "@winmaster_ofc",
    redeSocial: "X",
    dataPostagem: "2024-06-06 20:15:00",
    textoPostagem:
      "Acompanhe os resultados ao vivo na WinMaster! Oferecemos as melhores estatísticas para suas apostas. #WinMaster #AoVivo",
    linkPostagem: "https://x.com/winmaster_ofc/status/246801357",
    sentimento: "Neutro",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },

  // BetOnFire
  {
    empresa: "BetOnFire",
    perfil: "@betonfire",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-15 16:35:00",
    textoPostagem:
      "Aposte na BetOnFire e tenha 100% lucro! Nossa plataforma oferece certeza de lucro em todas as apostas, sem chance de perda! #BetOnFire",
    linkPostagem: "https://instagram.com/p/betonfire-13579",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [
      "100% lucro",
      "sem chance de perda",
      "certeza de lucro",
    ],
    violacaoTermos: true,
  },
  {
    empresa: "BetOnFire",
    perfil: "@betonfirebr",
    redeSocial: "X",
    dataPostagem: "2024-06-13 11:20:00",
    textoPostagem:
      "Novos jogos de cassino disponíveis! Venha se divertir na BetOnFire e aproveite nossos bônus exclusivos. #BetOnFire #Casino",
    linkPostagem: "https://x.com/betonfirebr/status/135792468",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },

  // GoldBets Club
  {
    empresa: "GoldBets Club",
    perfil: "@goldbetsclub",
    redeSocial: "Instagram",
    dataPostagem: "2024-06-11 14:55:00",
    textoPostagem:
      "Invista e ganhe com a GoldBets! Oferecemos segurança garantida e ganhos fixos para todos os apostadores. Comece agora! #GoldBets #Investimento",
    linkPostagem: "https://instagram.com/p/goldbetsclub-97531",
    sentimento: "Positivo",
    palavrasChaveEncontradas: [
      "invista e ganhe",
      "segurança garantida",
      "ganhos fixos",
    ],
    violacaoTermos: true,
  },
  {
    empresa: "GoldBets Club",
    perfil: "@goldbets_club",
    redeSocial: "X",
    dataPostagem: "2024-06-09 18:30:00",
    textoPostagem:
      "Acompanhe nossas análises esportivas diárias! A GoldBets Club traz informações exclusivas para melhorar suas apostas. #GoldBets #Análises",
    linkPostagem: "https://x.com/goldbets_club/status/864209753",
    sentimento: "Neutro",
    palavrasChaveEncontradas: [],
    violacaoTermos: false,
  },
];

// Dados de monitoramento de frequência de postagens
export const postFrequencyData = [
  {
    empresa: "BetMax Brasil",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 3 },
      { data: "2024-06-11", quantidadePostagens: 2 },
      { data: "2024-06-12", quantidadePostagens: 4 },
      { data: "2024-06-13", quantidadePostagens: 1 },
      { data: "2024-06-14", quantidadePostagens: 3 },
      { data: "2024-06-15", quantidadePostagens: 2 },
      { data: "2024-06-16", quantidadePostagens: 5 },
    ],
    mediaPostagens: 2.8,
    violacoesDetectadas: 4,
  },
  {
    empresa: "ApostaVip",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 4 },
      { data: "2024-06-11", quantidadePostagens: 3 },
      { data: "2024-06-12", quantidadePostagens: 5 },
      { data: "2024-06-13", quantidadePostagens: 2 },
      { data: "2024-06-14", quantidadePostagens: 3 },
      { data: "2024-06-15", quantidadePostagens: 4 },
      { data: "2024-06-16", quantidadePostagens: 3 },
    ],
    mediaPostagens: 3.4,
    violacoesDetectadas: 2,
  },
  {
    empresa: "TurboBets",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 1 },
      { data: "2024-06-11", quantidadePostagens: 2 },
      { data: "2024-06-12", quantidadePostagens: 1 },
      { data: "2024-06-13", quantidadePostagens: 0 },
      { data: "2024-06-14", quantidadePostagens: 3 },
      { data: "2024-06-15", quantidadePostagens: 1 },
      { data: "2024-06-16", quantidadePostagens: 2 },
    ],
    mediaPostagens: 1.4,
    violacoesDetectadas: 3,
  },
  {
    empresa: "MegaOddz",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 5 },
      { data: "2024-06-11", quantidadePostagens: 4 },
      { data: "2024-06-12", quantidadePostagens: 3 },
      { data: "2024-06-13", quantidadePostagens: 6 },
      { data: "2024-06-14", quantidadePostagens: 4 },
      { data: "2024-06-15", quantidadePostagens: 5 },
      { data: "2024-06-16", quantidadePostagens: 3 },
    ],
    mediaPostagens: 4.3,
    violacoesDetectadas: 5,
  },
  {
    empresa: "PlayBetNow",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 2 },
      { data: "2024-06-11", quantidadePostagens: 3 },
      { data: "2024-06-12", quantidadePostagens: 2 },
      { data: "2024-06-13", quantidadePostagens: 4 },
      { data: "2024-06-14", quantidadePostagens: 2 },
      { data: "2024-06-15", quantidadePostagens: 3 },
      { data: "2024-06-16", quantidadePostagens: 2 },
    ],
    mediaPostagens: 2.6,
    violacoesDetectadas: 2,
  },
  {
    empresa: "LuckZone",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 3 },
      { data: "2024-06-11", quantidadePostagens: 2 },
      { data: "2024-06-12", quantidadePostagens: 3 },
      { data: "2024-06-13", quantidadePostagens: 2 },
      { data: "2024-06-14", quantidadePostagens: 4 },
      { data: "2024-06-15", quantidadePostagens: 3 },
      { data: "2024-06-16", quantidadePostagens: 5 },
    ],
    mediaPostagens: 3.1,
    violacoesDetectadas: 3,
  },
  {
    empresa: "TopAposta360",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 1 },
      { data: "2024-06-11", quantidadePostagens: 1 },
      { data: "2024-06-12", quantidadePostagens: 2 },
      { data: "2024-06-13", quantidadePostagens: 1 },
      { data: "2024-06-14", quantidadePostagens: 0 },
      { data: "2024-06-15", quantidadePostagens: 1 },
      { data: "2024-06-16", quantidadePostagens: 1 },
    ],
    mediaPostagens: 1.0,
    violacoesDetectadas: 2,
  },
  {
    empresa: "WinMaster Bet",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 4 },
      { data: "2024-06-11", quantidadePostagens: 5 },
      { data: "2024-06-12", quantidadePostagens: 3 },
      { data: "2024-06-13", quantidadePostagens: 4 },
      { data: "2024-06-14", quantidadePostagens: 6 },
      { data: "2024-06-15", quantidadePostagens: 4 },
      { data: "2024-06-16", quantidadePostagens: 5 },
    ],
    mediaPostagens: 4.4,
    violacoesDetectadas: 6,
  },
  {
    empresa: "BetOnFire",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 2 },
      { data: "2024-06-11", quantidadePostagens: 3 },
      { data: "2024-06-12", quantidadePostagens: 2 },
      { data: "2024-06-13", quantidadePostagens: 2 },
      { data: "2024-06-14", quantidadePostagens: 3 },
      { data: "2024-06-15", quantidadePostagens: 4 },
      { data: "2024-06-16", quantidadePostagens: 2 },
    ],
    mediaPostagens: 2.6,
    violacoesDetectadas: 4,
  },
  {
    empresa: "GoldBets Club",
    redeSocial: "Instagram",
    ultimosDias: [
      { data: "2024-06-10", quantidadePostagens: 1 },
      { data: "2024-06-11", quantidadePostagens: 2 },
      { data: "2024-06-12", quantidadePostagens: 1 },
      { data: "2024-06-13", quantidadePostagens: 1 },
      { data: "2024-06-14", quantidadePostagens: 0 },
      { data: "2024-06-15", quantidadePostagens: 1 },
      { data: "2024-06-16", quantidadePostagens: 1 },
    ],
    mediaPostagens: 1.0,
    violacoesDetectadas: 3,
  },
];

// Dados de análise de conteúdo por empresa (continuação)
export const contentAnalysisData = [
  {
    empresa: "BetMax Brasil",
    totalPostagens: 45,
    postagensComViolacoes: 12,
    percentualViolacoes: 26.7,
    principaisTermosViolados: [
      { termo: "ganhe dinheiro fácil", ocorrencias: 8 },
      { termo: "aposta garantida", ocorrencias: 5 },
      { termo: "renda extra certa", ocorrencias: 3 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 60 },
      { rede: "X", percentual: 25 },
      { rede: "Facebook", percentual: 15 },
    ],
    tendenciaMensal: "crescente",
  },
  {
    empresa: "ApostaVip",
    totalPostagens: 62,
    postagensComViolacoes: 15,
    percentualViolacoes: 24.2,
    principaisTermosViolados: [
      { termo: "vitória assegurada", ocorrencias: 7 },
      { termo: "lucro sem risco", ocorrencias: 6 },
      { termo: "certeza de ganhar", ocorrencias: 4 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 55 },
      { rede: "X", percentual: 30 },
      { rede: "Telegram", percentual: 15 },
    ],
    tendenciaMensal: "estável",
  },
  {
    empresa: "TurboBets",
    totalPostagens: 38,
    postagensComViolacoes: 11,
    percentualViolacoes: 28.9,
    principaisTermosViolados: [
      { termo: "dinheiro fácil", ocorrencias: 6 },
      { termo: "renda fixa com apostas", ocorrencias: 3 },
      { termo: "aposta certeira", ocorrencias: 5 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 50 },
      { rede: "X", percentual: 20 },
      { rede: "Facebook", percentual: 30 },
    ],
    tendenciaMensal: "decrescente",
  },
  {
    empresa: "MegaOddz",
    totalPostagens: 75,
    postagensComViolacoes: 23,
    percentualViolacoes: 30.7,
    principaisTermosViolados: [
      { termo: "lucro garantido", ocorrencias: 10 },
      { termo: "dinheiro rápido", ocorrencias: 8 },
      { termo: "sem perder", ocorrencias: 9 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 65 },
      { rede: "X", percentual: 20 },
      { rede: "Telegram", percentual: 15 },
    ],
    tendenciaMensal: "crescente",
  },
  {
    empresa: "PlayBetNow",
    totalPostagens: 52,
    postagensComViolacoes: 14,
    percentualViolacoes: 26.9,
    principaisTermosViolados: [
      { termo: "ganhar sem risco", ocorrencias: 5 },
      { termo: "100% de retorno", ocorrencias: 7 },
      { termo: "investimento seguro", ocorrencias: 4 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 45 },
      { rede: "X", percentual: 35 },
      { rede: "Facebook", percentual: 20 },
    ],
    tendenciaMensal: "estável",
  },
  {
    empresa: "LuckZone",
    totalPostagens: 58,
    postagensComViolacoes: 18,
    percentualViolacoes: 31.0,
    principaisTermosViolados: [
      { termo: "renda garantida", ocorrencias: 8 },
      { termo: "faça dinheiro agora", ocorrencias: 7 },
      { termo: "certeza absoluta", ocorrencias: 5 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 60 },
      { rede: "X", percentual: 25 },
      { rede: "Discord", percentual: 15 },
    ],
    tendenciaMensal: "crescente",
  },
  {
    empresa: "TopAposta360",
    totalPostagens: 32,
    postagensComViolacoes: 9,
    percentualViolacoes: 28.1,
    principaisTermosViolados: [
      { termo: "aposta infalível", ocorrencias: 4 },
      { termo: "retorno certo", ocorrencias: 3 },
      { termo: "ganhos imediatos", ocorrencias: 3 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 40 },
      { rede: "X", percentual: 30 },
      { rede: "Facebook", percentual: 30 },
    ],
    tendenciaMensal: "decrescente",
  },
  {
    empresa: "WinMaster Bet",
    totalPostagens: 82,
    postagensComViolacoes: 27,
    percentualViolacoes: 32.9,
    principaisTermosViolados: [
      { termo: "fique rico apostando", ocorrencias: 11 },
      { termo: "lucro sem esforço", ocorrencias: 9 },
      { termo: "ganhar sempre", ocorrencias: 10 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 55 },
      { rede: "X", percentual: 30 },
      { rede: "Telegram", percentual: 15 },
    ],
    tendenciaMensal: "crescente",
  },
  {
    empresa: "BetOnFire",
    totalPostagens: 48,
    postagensComViolacoes: 16,
    percentualViolacoes: 33.3,
    principaisTermosViolados: [
      { termo: "100% lucro", ocorrencias: 7 },
      { termo: "sem chance de perda", ocorrencias: 5 },
      { termo: "certeza de lucro", ocorrencias: 6 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 50 },
      { rede: "X", percentual: 30 },
      { rede: "Facebook", percentual: 20 },
    ],
    tendenciaMensal: "estável",
  },
  {
    empresa: "GoldBets Club",
    totalPostagens: 29,
    postagensComViolacoes: 10,
    percentualViolacoes: 34.5,
    principaisTermosViolados: [
      { termo: "invista e ganhe", ocorrencias: 4 },
      { termo: "segurança garantida", ocorrencias: 3 },
      { termo: "ganhos fixos", ocorrencias: 5 },
    ],
    redesMaisUtilizadas: [
      { rede: "Instagram", percentual: 45 },
      { rede: "X", percentual: 35 },
      { rede: "Facebook", percentual: 20 },
    ],
    tendenciaMensal: "decrescente",
  },
];

// Dados de alertas de violação
export const violationAlerts = [
  {
    id: "VA001",
    empresa: "BetMax Brasil",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-16 09:45:23",
    termosViolados: ["ganhe dinheiro fácil"],
    linkPostagem: "https://instagram.com/p/betmaxbr12345",
    statusRevisao: "Pendente",
    prioridade: "Alta",
  },
  {
    id: "VA002",
    empresa: "WinMaster Bet",
    redeSocial: "X",
    dataDeteccao: "2024-06-16 10:12:45",
    termosViolados: ["fique rico apostando", "ganhar sempre"],
    linkPostagem: "https://x.com/winmaster_ofc/status/246801357",
    statusRevisao: "Em análise",
    prioridade: "Alta",
  },
  {
    id: "VA003",
    empresa: "MegaOddz",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-16 11:30:18",
    termosViolados: ["lucro garantido", "sem perder"],
    linkPostagem: "https://instagram.com/p/megaoddz24680",
    statusRevisao: "Pendente",
    prioridade: "Média",
  },
  {
    id: "VA004",
    empresa: "ApostaVip",
    redeSocial: "X",
    dataDeteccao: "2024-06-15 16:45:32",
    termosViolados: ["vitória assegurada"],
    linkPostagem: "https://x.com/vip_apostas/status/987654321",
    statusRevisao: "Concluída",
    prioridade: "Média",
  },
  {
    id: "VA005",
    empresa: "BetOnFire",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-15 14:22:10",
    termosViolados: ["100% lucro", "sem chance de perda", "certeza de lucro"],
    linkPostagem: "https://instagram.com/p/betonfire-13579",
    statusRevisao: "Em análise",
    prioridade: "Alta",
  },
  {
    id: "VA006",
    empresa: "LuckZone",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-16 08:55:42",
    termosViolados: ["renda garantida", "faça dinheiro agora"],
    linkPostagem: "https://instagram.com/p/luckzonebr86420",
    statusRevisao: "Pendente",
    prioridade: "Alta",
  },
  {
    id: "VA007",
    empresa: "TopAposta360",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-15 09:15:33",
    termosViolados: ["aposta infalível", "retorno certo", "ganhos imediatos"],
    linkPostagem: "https://instagram.com/p/topaposta360-97531",
    statusRevisao: "Concluída",
    prioridade: "Alta",
  },
  {
    id: "VA008",
    empresa: "TurboBets",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-14 17:40:21",
    termosViolados: ["dinheiro fácil"],
    linkPostagem: "https://instagram.com/p/turbobets67890",
    statusRevisao: "Concluída",
    prioridade: "Média",
  },
  {
    id: "VA009",
    empresa: "GoldBets Club",
    redeSocial: "Instagram",
    dataDeteccao: "2024-06-16 07:30:15",
    termosViolados: ["invista e ganhe", "segurança garantida", "ganhos fixos"],
    linkPostagem: "https://instagram.com/p/goldbetsclub-97531",
    statusRevisao: "Pendente",
    prioridade: "Alta",
  },
  {
    id: "VA010",
    empresa: "PlayBetNow",
    redeSocial: "X",
    dataDeteccao: "2024-06-15 13:10:55",
    termosViolados: [
      "ganhar sem risco",
      "100% de retorno",
      "investimento seguro",
    ],
    linkPostagem: "https://x.com/playbet_oficial/status/975318642",
    statusRevisao: "Em análise",
    prioridade: "Alta",
  },
];

// Dados de histórico de monitoramento (continuação)
export const monitoringHistory = [
  {
    empresa: "BetMax Brasil",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 42,
    violacoesDetectadas: 10,
    percentualViolacoes: 23.8,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "BetMax Brasil",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 45,
    violacoesDetectadas: 12,
    percentualViolacoes: 26.7,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "ApostaVip",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 58,
    violacoesDetectadas: 13,
    percentualViolacoes: 22.4,
    redesMonitoradas: ["Instagram", "X", "Telegram"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "ApostaVip",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 62,
    violacoesDetectadas: 15,
    percentualViolacoes: 24.2,
    redesMonitoradas: ["Instagram", "X", "Telegram"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "TurboBets",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 35,
    violacoesDetectadas: 12,
    percentualViolacoes: 34.3,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "TurboBets",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 38,
    violacoesDetectadas: 11,
    percentualViolacoes: 28.9,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "MegaOddz",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 70,
    violacoesDetectadas: 20,
    percentualViolacoes: 28.6,
    redesMonitoradas: ["Instagram", "X", "Telegram"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "MegaOddz",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 75,
    violacoesDetectadas: 23,
    percentualViolacoes: 30.7,
    redesMonitoradas: ["Instagram", "X", "Telegram"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "PlayBetNow",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 48,
    violacoesDetectadas: 12,
    percentualViolacoes: 25.0,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "PlayBetNow",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 52,
    violacoesDetectadas: 14,
    percentualViolacoes: 26.9,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "LuckZone",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 55,
    violacoesDetectadas: 16,
    percentualViolacoes: 29.1,
    redesMonitoradas: ["Instagram", "X", "Discord"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "LuckZone",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 58,
    violacoesDetectadas: 18,
    percentualViolacoes: 31.0,
    redesMonitoradas: ["Instagram", "X", "Discord"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "TopAposta360",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 30,
    violacoesDetectadas: 8,
    percentualViolacoes: 26.7,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "TopAposta360",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 32,
    violacoesDetectadas: 9,
    percentualViolacoes: 28.1,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "WinMaster Bet",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 78,
    violacoesDetectadas: 24,
    percentualViolacoes: 30.8,
    redesMonitoradas: ["Instagram", "X", "Telegram"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "WinMaster Bet",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 82,
    violacoesDetectadas: 27,
    percentualViolacoes: 32.9,
    redesMonitoradas: ["Instagram", "X", "Telegram"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "BetOnFire",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 45,
    violacoesDetectadas: 14,
    percentualViolacoes: 31.1,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "BetOnFire",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 48,
    violacoesDetectadas: 16,
    percentualViolacoes: 33.3,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Em andamento",
  },
  {
    empresa: "GoldBets Club",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    totalPostagens: 27,
    violacoesDetectadas: 9,
    percentualViolacoes: 33.3,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Concluído",
  },
  {
    empresa: "GoldBets Club",
    periodoInicio: "2024-06-01",
    periodoFim: "2024-06-16",
    totalPostagens: 29,
    violacoesDetectadas: 10,
    percentualViolacoes: 34.5,
    redesMonitoradas: ["Instagram", "X", "Facebook"],
    statusMonitoramento: "Em andamento",
  },
];

// Dados de relatórios de compliance (continuação)
export const complianceReports = [
  {
    id: "CR001",
    empresa: "BetMax Brasil",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-05",
    statusCompliance: "Não conforme",
    nivelRisco: "Alto",
    recomendacoes: [
      "Revisar todas as postagens contendo os termos 'ganhe dinheiro fácil' e 'aposta garantida'",
      "Implementar processo de aprovação prévia para postagens em redes sociais",
      "Realizar treinamento com equipe de marketing sobre regulamentações",
    ],
    prazoAdequacao: "2024-06-20",
    statusAcao: "Em andamento",
  },
  {
    id: "CR002",
    empresa: "ApostaVip",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-05",
    statusCompliance: "Parcialmente conforme",
    nivelRisco: "Médio",
    recomendacoes: [
      "Remover postagens contendo o termo 'vitória assegurada'",
      "Revisar diretrizes de comunicação em redes sociais",
    ],
    prazoAdequacao: "2024-06-15",
    statusAcao: "Concluído",
  },
  {
    id: "CR003",
    empresa: "TurboBets",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-06",
    statusCompliance: "Não conforme",
    nivelRisco: "Alto",
    recomendacoes: [
      "Remover todas as postagens com termos proibidos",
      "Implementar sistema de verificação prévia de conteúdo",
      "Realizar treinamento com equipe de marketing",
    ],
    prazoAdequacao: "2024-06-25",
    statusAcao: "Em andamento",
  },
  {
    id: "CR004",
    empresa: "MegaOddz",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-06",
    statusCompliance: "Não conforme",
    nivelRisco: "Alto",
    recomendacoes: [
      "Remover todas as postagens com os termos 'lucro garantido' e 'sem perder'",
      "Revisar estratégia de comunicação em redes sociais",
      "Implementar processo de aprovação prévia para postagens",
    ],
    prazoAdequacao: "2024-06-30",
    statusAcao: "Não iniciado",
  },
  {
    id: "CR005",
    empresa: "PlayBetNow",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-07",
    statusCompliance: "Parcialmente conforme",
    nivelRisco: "Médio",
    recomendacoes: [
      "Revisar postagens contendo termos proibidos",
      "Implementar diretrizes claras para comunicação em redes sociais",
    ],
    prazoAdequacao: "2024-06-22",
    statusAcao: "Em andamento",
  },
  {
    id: "CR006",
    empresa: "LuckZone",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-07",
    statusCompliance: "Não conforme",
    nivelRisco: "Alto",
    recomendacoes: [
      "Remover todas as postagens com termos proibidos",
      "Implementar processo de revisão de conteúdo",
      "Realizar treinamento com equipe de marketing",
    ],
    prazoAdequacao: "2024-06-28",
    statusAcao: "Em andamento",
  },
  {
    id: "CR007",
    empresa: "TopAposta360",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-08",
    statusCompliance: "Parcialmente conforme",
    nivelRisco: "Médio",
    recomendacoes: [
      "Revisar postagens contendo os termos 'aposta infalível' e 'retorno certo'",
      "Implementar diretrizes para comunicação responsável",
    ],
    prazoAdequacao: "2024-06-20",
    statusAcao: "Concluído",
  },
  {
    id: "CR008",
    empresa: "WinMaster Bet",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-08",
    statusCompliance: "Não conforme",
    nivelRisco: "Crítico",
    recomendacoes: [
      "Remover imediatamente todas as postagens com termos proibidos",
      "Implementar processo rigoroso de aprovação de conteúdo",
      "Realizar treinamento obrigatório com toda equipe de marketing",
      "Estabelecer monitoramento contínuo de todas as redes sociais",
    ],
    prazoAdequacao: "2024-06-15",
    statusAcao: "Em andamento",
  },
  {
    id: "CR009",
    empresa: "BetOnFire",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-09",
    statusCompliance: "Não conforme",
    nivelRisco: "Alto",
    recomendacoes: [
      "Remover todas as postagens com termos proibidos",
      "Revisar estratégia de comunicação em redes sociais",
      "Implementar processo de aprovação prévia para postagens",
    ],
    prazoAdequacao: "2024-06-25",
    statusAcao: "Não iniciado",
  },
  {
    id: "CR010",
    empresa: "GoldBets Club",
    periodoInicio: "2024-05-01",
    periodoFim: "2024-05-31",
    dataEmissao: "2024-06-09",
    statusCompliance: "Não conforme",
    nivelRisco: "Alto",
    recomendacoes: [
      "Remover todas as postagens com termos proibidos",
      "Implementar processo de aprovação de conteúdo",
      "Realizar treinamento com equipe de marketing",
    ],
    prazoAdequacao: "2024-06-23",
    statusAcao: "Em andamento",
  },
];

// Dados de agendamentos de monitoramento (continuação)
export const monitoringSchedules = [
  {
    id: "MS001",
    empresa: "BetMax Brasil",
    dataAgendamento: "2024-06-18 09:00:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Ana Silva",
    status: "Agendado",
    observacoes: "Monitorar especialmente os termos proibidos recorrentes",
  },
  {
    id: "MS002",
    empresa: "BetMax Brasil",
    dataAgendamento: "2024-06-21 14:00:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Ana Silva",
    status: "Agendado",
    observacoes: "Verificar se as recomendações anteriores foram implementadas",
  },
  {
    id: "MS003",
    empresa: "ApostaVip",
    dataAgendamento: "2024-06-19 10:30:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Carlos Mendes",
    status: "Agendado",
    observacoes: "Focar nas postagens promocionais recentes",
  },
  {
    id: "MS004",
    empresa: "ApostaVip",
    dataAgendamento: "2024-06-22 11:00:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Parcial",
    responsavel: "Carlos Mendes",
    status: "Agendado",
    observacoes: "Verificar apenas postagens com alto engajamento",
  },
  {
    id: "MS005",
    empresa: "ApostaVip",
    dataAgendamento: "2024-06-25 15:30:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Carlos Mendes",
    status: "Agendado",
    observacoes: "Monitoramento de rotina",
  },
  {
    id: "MS006",
    empresa: "TurboBets",
    dataAgendamento: "2024-06-20 09:15:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Mariana Costa",
    status: "Agendado",
    observacoes: "Verificar implementação das recomendações do relatório CR003",
  },
  {
    id: "MS007",
    empresa: "MegaOddz",
    dataAgendamento: "2024-06-17 13:00:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Pedro Santos",
    status: "Agendado",
    observacoes: "Monitoramento prioritário devido ao alto número de violações",
  },
  {
    id: "MS008",
    empresa: "MegaOddz",
    dataAgendamento: "2024-06-20 14:30:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Pedro Santos",
    status: "Agendado",
    observacoes: "Verificar novas postagens após notificação de violação",
  },
  {
    id: "MS009",
    empresa: "MegaOddz",
    dataAgendamento: "2024-06-23 10:00:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Pedro Santos",
    status: "Agendado",
    observacoes: "Monitoramento de rotina",
  },
  {
    id: "MS010",
    empresa: "PlayBetNow",
    dataAgendamento: "2024-06-19 16:00:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Juliana Alves",
    status: "Agendado",
    observacoes: "Verificar implementação das recomendações do relatório CR005",
  },
  {
    id: "MS011",
    empresa: "PlayBetNow",
    dataAgendamento: "2024-06-22 09:30:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Parcial",
    responsavel: "Juliana Alves",
    status: "Agendado",
    observacoes: "Focar em postagens promocionais",
  },
  {
    id: "MS012",
    empresa: "LuckZone",
    dataAgendamento: "2024-06-18 11:30:00",
    redesMonitorar: ["Instagram", "X", "Discord"],
    tipoMonitoramento: "Completo",
    responsavel: "Rafael Lima",
    status: "Agendado",
    observacoes:
      "Monitorar especialmente os termos 'renda garantida' e 'faça dinheiro agora'",
  },
  {
    id: "MS013",
    empresa: "LuckZone",
    dataAgendamento: "2024-06-21 10:00:00",
    redesMonitorar: ["Instagram", "X", "Discord"],
    tipoMonitoramento: "Completo",
    responsavel: "Rafael Lima",
    status: "Agendado",
    observacoes: "Verificar implementação das recomendações do relatório CR006",
  },
  {
    id: "MS014",
    empresa: "TopAposta360",
    dataAgendamento: "2024-06-17 09:00:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Fernanda Oliveira",
    status: "Agendado",
    observacoes: "Monitoramento de rotina",
  },
  {
    id: "MS015",
    empresa: "WinMaster Bet",
    dataAgendamento: "2024-06-17 10:30:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Lucas Martins",
    status: "Agendado",
    observacoes: "Monitoramento prioritário devido ao nível de risco crítico",
  },
  {
    id: "MS016",
    empresa: "WinMaster Bet",
    dataAgendamento: "2024-06-19 14:00:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Lucas Martins",
    status: "Agendado",
    observacoes: "Verificar remoção de postagens com termos proibidos",
  },
  {
    id: "MS017",
    empresa: "WinMaster Bet",
    dataAgendamento: "2024-06-22 13:30:00",
    redesMonitorar: ["Instagram", "X", "Telegram"],
    tipoMonitoramento: "Completo",
    responsavel: "Lucas Martins",
    status: "Agendado",
    observacoes: "Monitoramento de acompanhamento após prazo de adequação",
  },
  {
    id: "MS018",
    empresa: "BetOnFire",
    dataAgendamento: "2024-06-18 15:00:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Camila Rocha",
    status: "Agendado",
    observacoes: "Primeiro monitoramento após emissão do relatório CR009",
  },
  {
    id: "MS019",
    empresa: "BetOnFire",
    dataAgendamento: "2024-06-21 16:30:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Camila Rocha",
    status: "Agendado",
    observacoes: "Verificar início da implementação das recomendações",
  },
  {
    id: "MS020",
    empresa: "GoldBets Club",
    dataAgendamento: "2024-06-17 14:30:00",
    redesMonitorar: ["Instagram", "X", "Facebook"],
    tipoMonitoramento: "Completo",
    responsavel: "Bruno Almeida",
    status: "Agendado",
    observacoes:
      "Monitoramento de acompanhamento após emissão do relatório CR010",
  },
];

// Dados de estatísticas gerais do sistema
export const systemStats = {
  totalEmpresas: 10,
  totalMonitoramentos: 245,
  totalViolacoes: 145,
  percentualViolacoes: 28.6,
  redesMaisMonitoradas: [
    { rede: "Instagram", percentual: 55 },
    { rede: "X", percentual: 25 },
    { rede: "Facebook", percentual: 12 },
    { rede: "Telegram", percentual: 5 },
    { rede: "Discord", percentual: 3 },
  ],
  termosProibidosMaisComuns: [
    { termo: "lucro garantido", ocorrencias: 42 },
    { termo: "ganhe dinheiro fácil", ocorrencias: 38 },
    { termo: "aposta garantida", ocorrencias: 35 },
    { termo: "sem perder", ocorrencias: 30 },
    { termo: "renda garantida", ocorrencias: 28 },
  ],
  empresasMaisViolacoes: [
    { empresa: "WinMaster Bet", percentual: 32.9 },
    { empresa: "GoldBets Club", percentual: 34.5 },
    { empresa: "BetOnFire", percentual: 33.3 },
    { empresa: "LuckZone", percentual: 31.0 },
    { empresa: "MegaOddz", percentual: 30.7 },
  ],
  tendenciaViolacoes: [
    { mes: "Janeiro", quantidade: 110 },
    { mes: "Fevereiro", quantidade: 125 },
    { mes: "Março", quantidade: 118 },
    { mes: "Abril", quantidade: 132 },
    { mes: "Maio", quantidade: 145 },
    { mes: "Junho (parcial)", quantidade: 78 },
  ],
};

// Dados de logs do sistema (continuação)
export const systemLogs = [
  {
    id: "LOG001",
    timestamp: "2024-06-16 08:45:12",
    usuario: "Ana Silva",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.45",
  },
  {
    id: "LOG002",
    timestamp: "2024-06-16 08:47:30",
    usuario: "Ana Silva",
    acao: "Acesso ao módulo de monitoramento",
    detalhes: "Visualização da lista de empresas",
    ip: "192.168.1.45",
  },
  {
    id: "LOG003",
    timestamp: "2024-06-16 08:50:15",
    usuario: "Ana Silva",
    acao: "Agendamento de monitoramento",
    detalhes: "Criação do agendamento MS001 para BetMax Brasil",
    ip: "192.168.1.45",
  },
  {
    id: "LOG004",
    timestamp: "2024-06-16 09:12:35",
    usuario: "Carlos Mendes",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.62",
  },
  {
    id: "LOG005",
    timestamp: "2024-06-16 09:15:22",
    usuario: "Carlos Mendes",
    acao: "Acesso ao módulo de alertas",
    detalhes: "Visualização de alertas pendentes",
    ip: "192.168.1.62",
  },
  {
    id: "LOG006",
    timestamp: "2024-06-16 09:20:45",
    usuario: "Carlos Mendes",
    acao: "Atualização de alerta",
    detalhes: "Alteração do status do alerta VA003 para 'Em análise'",
    ip: "192.168.1.62",
  },
  {
    id: "LOG007",
    timestamp: "2024-06-16 09:30:55",
    usuario: "Rafael Lima",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.78",
  },
  {
    id: "LOG008",
    timestamp: "2024-06-16 09:35:10",
    usuario: "Rafael Lima",
    acao: "Acesso ao módulo de relatórios",
    detalhes: "Geração de relatório para LuckZone",
    ip: "192.168.1.78",
  },
  {
    id: "LOG009",
    timestamp: "2024-06-16 09:45:30",
    usuario: "Rafael Lima",
    acao: "Exportação de relatório",
    detalhes: "Exportação em formato PDF do relatório de LuckZone",
    ip: "192.168.1.78",
  },
  {
    id: "LOG010",
    timestamp: "2024-06-16 09:55:18",
    usuario: "Bruno Almeida",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.90",
  },
  {
    id: "LOG011",
    timestamp: "2024-06-16 10:00:25",
    usuario: "Bruno Almeida",
    acao: "Acesso ao módulo de monitoramento",
    detalhes: "Visualização de agendamentos",
    ip: "192.168.1.90",
  },
  {
    id: "LOG012",
    timestamp: "2024-06-16 10:05:47",
    usuario: "Pedro Santos",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.105",
  },
  {
    id: "LOG013",
    timestamp: "2024-06-16 10:10:33",
    usuario: "Pedro Santos",
    acao: "Acesso ao módulo de alertas",
    detalhes: "Visualização de alertas para MegaOddz",
    ip: "192.168.1.105",
  },
  {
    id: "LOG014",
    timestamp: "2024-06-16 10:20:15",
    usuario: "Pedro Santos",
    acao: "Atualização de alerta",
    detalhes: "Alteração do status do alerta VA003 para 'Concluído'",
    ip: "192.168.1.105",
  },
  {
    id: "LOG015",
    timestamp: "2024-06-16 10:45:22",
    usuario: "Marcelo Souza",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.120",
  },
  {
    id: "LOG016",
    timestamp: "2024-06-16 10:50:40",
    usuario: "Marcelo Souza",
    acao: "Acesso ao módulo de administração",
    detalhes: "Visualização de configurações do sistema",
    ip: "192.168.1.120",
  },
  {
    id: "LOG017",
    timestamp: "2024-06-16 11:00:15",
    usuario: "Marcelo Souza",
    acao: "Atualização de configurações",
    detalhes: "Alteração nas configurações de monitoramento automático",
    ip: "192.168.1.120",
  },
  {
    id: "LOG018",
    timestamp: "2024-06-16 11:20:45",
    usuario: "Roberto Gomes",
    acao: "Login no sistema",
    detalhes: "Login bem-sucedido",
    ip: "192.168.1.135",
  },
  {
    id: "LOG019",
    timestamp: "2024-06-16 11:25:30",
    usuario: "Roberto Gomes",
    acao: "Acesso ao módulo de relatórios",
    detalhes: "Visualização de relatórios gerenciais",
    ip: "192.168.1.135",
  },
  {
    id: "LOG020",
    timestamp: "2024-06-16 11:35:20",
    usuario: "Roberto Gomes",
    acao: "Exportação de relatório",
    detalhes: "Exportação em formato Excel do relatório gerencial mensal",
    ip: "192.168.1.135",
  },
];

// Dados de estatísticas de monitoramento por empresa (continuação)
export const companyMonitoringStats = [
  {
    empresa: "BetMax Brasil",
    totalMonitoramentos: 32,
    totalViolacoes: 18,
    percentualViolacoes: 56.3,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 65 },
      { rede: "X", percentual: 25 },
      { rede: "Facebook", percentual: 10 },
    ],
    termosProibidosMaisComuns: [
      { termo: "ganhe dinheiro fácil", ocorrencias: 8 },
      { termo: "aposta garantida", ocorrencias: 6 },
      { termo: "renda extra certa", ocorrencias: 4 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 2 },
      { mes: "Fevereiro", quantidade: 3 },
      { mes: "Março", quantidade: 2 },
      { mes: "Abril", quantidade: 4 },
      { mes: "Maio", quantidade: 5 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "ApostaVip",
    totalMonitoramentos: 28,
    totalViolacoes: 15,
    percentualViolacoes: 53.6,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 60 },
      { rede: "Telegram", percentual: 25 },
      { rede: "X", percentual: 15 },
    ],
    termosProibidosMaisComuns: [
      { termo: "vitória assegurada", ocorrencias: 7 },
      { termo: "lucro sem risco", ocorrencias: 5 },
      { termo: "certeza de ganhar", ocorrencias: 3 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 2 },
      { mes: "Março", quantidade: 3 },
      { mes: "Abril", quantidade: 3 },
      { mes: "Maio", quantidade: 4 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "TurboBets",
    totalMonitoramentos: 20,
    totalViolacoes: 12,
    percentualViolacoes: 60.0,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 55 },
      { rede: "X", percentual: 35 },
      { rede: "Facebook", percentual: 10 },
    ],
    termosProibidosMaisComuns: [
      { termo: "dinheiro fácil", ocorrencias: 6 },
      { termo: "renda fixa com apostas", ocorrencias: 4 },
      { termo: "aposta certeira", ocorrencias: 2 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 1 },
      { mes: "Março", quantidade: 2 },
      { mes: "Abril", quantidade: 3 },
      { mes: "Maio", quantidade: 3 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "MegaOddz",
    totalMonitoramentos: 30,
    totalViolacoes: 18,
    percentualViolacoes: 60.0,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 50 },
      { rede: "Telegram", percentual: 30 },
      { rede: "X", percentual: 20 },
    ],
    termosProibidosMaisComuns: [
      { termo: "lucro garantido", ocorrencias: 8 },
      { termo: "dinheiro rápido", ocorrencias: 6 },
      { termo: "sem perder", ocorrencias: 4 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 2 },
      { mes: "Fevereiro", quantidade: 3 },
      { mes: "Março", quantidade: 3 },
      { mes: "Abril", quantidade: 4 },
      { mes: "Maio", quantidade: 4 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "PlayBetNow",
    totalMonitoramentos: 25,
    totalViolacoes: 14,
    percentualViolacoes: 56.0,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 60 },
      { rede: "Facebook", percentual: 25 },
      { rede: "X", percentual: 15 },
    ],
    termosProibidosMaisComuns: [
      { termo: "ganhar sem risco", ocorrencias: 7 },
      { termo: "100% de retorno", ocorrencias: 4 },
      { termo: "investimento seguro", ocorrencias: 3 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 2 },
      { mes: "Março", quantidade: 2 },
      { mes: "Abril", quantidade: 3 },
      { mes: "Maio", quantidade: 4 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "LuckZone",
    totalMonitoramentos: 22,
    totalViolacoes: 13,
    percentualViolacoes: 59.1,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 55 },
      { rede: "Discord", percentual: 25 },
      { rede: "X", percentual: 20 },
    ],
    termosProibidosMaisComuns: [
      { termo: "renda garantida", ocorrencias: 6 },
      { termo: "faça dinheiro agora", ocorrencias: 4 },
      { termo: "certeza absoluta", ocorrencias: 3 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 2 },
      { mes: "Março", quantidade: 2 },
      { mes: "Abril", quantidade: 3 },
      { mes: "Maio", quantidade: 3 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "TopAposta360",
    totalMonitoramentos: 18,
    totalViolacoes: 10,
    percentualViolacoes: 55.6,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 60 },
      { rede: "X", percentual: 30 },
      { rede: "Facebook", percentual: 10 },
    ],
    termosProibidosMaisComuns: [
      { termo: "aposta infalível", ocorrencias: 5 },
      { termo: "retorno certo", ocorrencias: 3 },
      { termo: "ganhos imediatos", ocorrencias: 2 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 1 },
      { mes: "Março", quantidade: 2 },
      { mes: "Abril", quantidade: 2 },
      { mes: "Maio", quantidade: 3 },
      { mes: "Junho (parcial)", quantidade: 1 },
    ],
  },
  {
    empresa: "WinMaster Bet",
    totalMonitoramentos: 30,
    totalViolacoes: 19,
    percentualViolacoes: 63.3,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 50 },
      { rede: "Telegram", percentual: 30 },
      { rede: "X", percentual: 20 },
    ],
    termosProibidosMaisComuns: [
      { termo: "fique rico apostando", ocorrencias: 8 },
      { termo: "lucro sem esforço", ocorrencias: 6 },
      { termo: "ganhar sempre", ocorrencias: 5 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 2 },
      { mes: "Fevereiro", quantidade: 3 },
      { mes: "Março", quantidade: 3 },
      { mes: "Abril", quantidade: 4 },
      { mes: "Maio", quantidade: 5 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "BetOnFire",
    totalMonitoramentos: 24,
    totalViolacoes: 15,
    percentualViolacoes: 62.5,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 55 },
      { rede: "Facebook", percentual: 30 },
      { rede: "X", percentual: 15 },
    ],
    termosProibidosMaisComuns: [
      { termo: "100% lucro", ocorrencias: 7 },
      { termo: "sem chance de perda", ocorrencias: 5 },
      { termo: "certeza de lucro", ocorrencias: 3 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 2 },
      { mes: "Março", quantidade: 3 },
      { mes: "Abril", quantidade: 3 },
      { mes: "Maio", quantidade: 4 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
  {
    empresa: "GoldBets Club",
    totalMonitoramentos: 16,
    totalViolacoes: 11,
    percentualViolacoes: 68.8,
    redesMaisViolacoes: [
      { rede: "Instagram", percentual: 60 },
      { rede: "X", percentual: 30 },
      { rede: "Facebook", percentual: 10 },
    ],
    termosProibidosMaisComuns: [
      { termo: "invista e ganhe", ocorrencias: 5 },
      { termo: "segurança garantida", ocorrencias: 4 },
      { termo: "ganhos fixos", ocorrencias: 2 },
    ],
    tendenciaViolacoes: [
      { mes: "Janeiro", quantidade: 1 },
      { mes: "Fevereiro", quantidade: 1 },
      { mes: "Março", quantidade: 2 },
      { mes: "Abril", quantidade: 2 },
      { mes: "Maio", quantidade: 3 },
      { mes: "Junho (parcial)", quantidade: 2 },
    ],
  },
];

// Dados de monitoramentos agendados
export const scheduledMonitorings = [
  {
    id: "MS001",
    empresa: "BetMax Brasil",
    redesSociais: ["Instagram", "X", "Facebook"],
    dataAgendamento: "2024-06-17 08:00:00",
    frequencia: "Semanal",
    responsavel: "Ana Silva",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-17 08:00:00",
  },
  {
    id: "MS002",
    empresa: "ApostaVip",
    redesSociais: ["Instagram", "X", "Telegram", "Facebook"],
    dataAgendamento: "2024-06-17 10:00:00",
    frequencia: "Semanal",
    responsavel: "Carlos Mendes",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-17 10:00:00",
  },
  {
    id: "MS003",
    empresa: "TurboBets",
    redesSociais: ["Instagram", "X", "Facebook"],
    dataAgendamento: "2024-06-18 08:00:00",
    frequencia: "Semanal",
    responsavel: "Mariana Costa",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-18 08:00:00",
  },
  {
    id: "MS004",
    empresa: "MegaOddz",
    redesSociais: ["Instagram", "Telegram", "X", "Facebook"],
    dataAgendamento: "2024-06-18 10:00:00",
    frequencia: "Semanal",
    responsavel: "Pedro Santos",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-18 10:00:00",
  },
  {
    id: "MS005",
    empresa: "PlayBetNow",
    redesSociais: ["Instagram", "Facebook", "X"],
    dataAgendamento: "2024-06-19 08:00:00",
    frequencia: "Semanal",
    responsavel: "Juliana Alves",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-19 08:00:00",
  },
  {
    id: "MS006",
    empresa: "LuckZone",
    redesSociais: ["Instagram", "Discord", "X", "Facebook"],
    dataAgendamento: "2024-06-19 10:00:00",
    frequencia: "Semanal",
    responsavel: "Rafael Lima",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-19 10:00:00",
  },
  {
    id: "MS007",
    empresa: "TopAposta360",
    redesSociais: ["Instagram", "X", "Facebook"],
    dataAgendamento: "2024-06-20 08:00:00",
    frequencia: "Semanal",
    responsavel: "Fernanda Oliveira",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-20 08:00:00",
  },
  {
    id: "MS008",
    empresa: "WinMaster Bet",
    redesSociais: ["Instagram", "Telegram", "X", "Facebook"],
    dataAgendamento: "2024-06-20 10:00:00",
    frequencia: "Semanal",
    responsavel: "Lucas Martins",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-20 10:00:00",
  },
  {
    id: "MS009",
    empresa: "BetOnFire",
    redesSociais: ["Instagram", "Facebook", "X"],
    dataAgendamento: "2024-06-21 08:00:00",
    frequencia: "Semanal",
    responsavel: "Camila Rocha",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-21 08:00:00",
  },
  {
    id: "MS010",
    empresa: "GoldBets Club",
    redesSociais: ["Instagram", "X", "Facebook"],
    dataAgendamento: "2024-06-21 10:00:00",
    frequencia: "Semanal",
    responsavel: "Bruno Almeida",
    status: "Agendado",
    ultimaExecucao: null,
    proximaExecucao: "2024-06-21 10:00:00",
  },
];

// Adicionar ao arquivo existente ou criar se não existir

// KPIs das bases de dados
export const databaseKPIs = {
  connectedDatabases: 15,
  totalRecords: 125000000,
  breakdown: {
    cpf: 89000000,
    cnpj: 8500000,
    genderMale: 54000000,
    genderFemale: 35000000,
    ageRanges: {
      "18-25": 320000,
      "26-35": 450000,
      "36-45": 380000,
      "46-55": 290000,
      "56-65": 180000,
      "65+": 130000,
    },
    cellphones: 121000000,
    emails: 132000000,
    criminalRecords: 2100000,
    civilLawsuits: 120000,
    properties: 5400000,
    vehicles: 18000000,
    adicto: 1300000,
    dopaminado: 4700000,
    ludopata: 450000,
    bankAccounts: 780000,
    socialMedia: 1500000,
    peps: 8500,
    sancionados: 2900,
    obitos: 4300000,
    redesSociais: 12000000,
    empresasAtivas: 7200000,
    empresasInativas: 1300000,
    microEmpresas: 6800000,
    pequenasEmpresas: 1500000,
    mediasEmpresas: 180000,
    grandesEmpresas: 20000,
  },
};

// Exemplos de busca com dicas
export const searchExamples = [
  {
    id: 1,
    title: "Violações de Trânsito",
    description: "Busque por violações de trânsito no CPF",
    example: "123.456.789-00",
    category: "traffic",
  },
  {
    id: 2,
    title: "Processos Judiciais",
    description: "Consulte processos em nome de",
    example: "João Silva Santos",
    category: "legal",
  },
  {
    id: 3,
    title: "Dados Empresariais",
    description: "Informações da empresa CNPJ",
    example: "11.222.333/0001-81",
    category: "business",
  },
  {
    id: 4,
    title: "Consulta de Empresa",
    description: "Busque dados de empresas conhecidas",
    example: "Magazine Luiza",
    category: "business",
  },
  {
    id: 5,
    title: "Grandes Corporações",
    description: "Consulte informações de grandes empresas",
    example: "Petrobras",
    category: "business",
  },
  {
    id: 6,
    title: "Propriedades Imobiliárias",
    description: "Imóveis registrados em nome de",
    example: "Maria Oliveira Costa",
    category: "property",
  },
];

// Função para gerar resultados baseados em diferentes tipos de consulta
export const getIntelligentSearchResults = (searchTerm) => {
  const lowerTerm = searchTerm.toLowerCase();

  // Resultados para violações de trânsito
  if (
    lowerTerm.includes("violaç") ||
    lowerTerm.includes("transito") ||
    lowerTerm.includes("trânsito") ||
    lowerTerm.includes("multa")
  ) {
    return [
      {
        id: 1,
        category: "Violações de Trânsito",
        source: "DETRAN-SP",
        field: "Excesso de Velocidade",
        value: "R$ 195,23 - Rodovia Anhanguera, KM 45 - 12/12/2023",
        confidence: 98,
        lastUpdate: "2023-12-13T09:15:00Z",
        verified: true,
      },
      {
        id: 2,
        category: "Violações de Trânsito",
        source: "DETRAN-RJ",
        field: "Estacionamento Irregular",
        value: "R$ 88,38 - Rua Copacabana, 150 - 05/11/2023",
        confidence: 95,
        lastUpdate: "2023-11-06T16:45:00Z",
        verified: true,
      },
      {
        id: 3,
        category: "Violações de Trânsito",
        source: "DETRAN-MG",
        field: "Avanço de Sinal Vermelho",
        value: "R$ 293,47 - Av. Afonso Pena - 28/10/2023",
        confidence: 92,
        lastUpdate: "2023-10-29T14:20:00Z",
        verified: true,
      },
      {
        id: 4,
        category: "Dados Pessoais",
        source: "DETRAN-SP",
        field: "CNH Categoria B",
        value: "Válida até 15/08/2027 - 8 pontos na carteira",
        confidence: 99,
        lastUpdate: "2024-01-15T10:30:00Z",
        verified: true,
      },
      {
        id: 5,
        category: "Veículos",
        source: "DETRAN-SP",
        field: "Honda Civic 2020",
        value: "Placa: ABC-1234 - Licenciado 2024",
        confidence: 97,
        lastUpdate: "2024-01-05T13:20:00Z",
        verified: true,
      },
    ];
  }

  // Resultados para processos judiciais
  if (
    lowerTerm.includes("processo") ||
    lowerTerm.includes("judicial") ||
    lowerTerm.includes("tribunal")
  ) {
    return [
      {
        id: 6,
        category: "Processos Judiciais",
        source: "TJSP",
        field: "Ação de Cobrança",
        value: "Processo: 1234567-89.2023.8.26.0100 - Em andamento",
        confidence: 94,
        lastUpdate: "2023-09-20T15:10:00Z",
        verified: true,
      },
      {
        id: 7,
        category: "Processos Judiciais",
        source: "TJRJ",
        field: "Ação Trabalhista",
        value: "Processo: 9876543-21.2022.5.01.0001 - Arquivado",
        confidence: 91,
        lastUpdate: "2022-12-15T11:30:00Z",
        verified: true,
      },
      {
        id: 8,
        category: "Dados Pessoais",
        source: "TSE",
        field: "Situação Eleitoral",
        value: "Regular - Última votação: 02/10/2022",
        confidence: 96,
        lastUpdate: "2022-10-03T08:00:00Z",
        verified: true,
      },
    ];
  }

  // Resultados para CNPJ/empresas
  if (
    lowerTerm.includes("cnpj") ||
    lowerTerm.includes("empresa") ||
    /\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}/.test(searchTerm)
  ) {
    // Simular diferentes empresas baseadas no termo de busca
    const empresas = [
      {
        cnpj: "11.222.333/0001-81",
        razaoSocial: "MAGAZINE LUIZA S.A.",
        nomeFantasia: "Magazine Luiza",
        porte: "GRANDE",
        capital: "R$ 925.250.000,00",
        situacao: "ATIVA",
        dataAbertura: "02/05/1957",
        cnae: "47.12-1/00 - Comércio varejista de mercadorias em geral",
        endereco: "Rua Voluntários da Franca, 1465 - Franca/SP",
        telefone: "(16) 3711-1000",
        socios: [
          "Luiza Helena Trajano Inácio Rodrigues - 12,5%",
          "Frederico Trajano Inácio Rodrigues - 8,2%",
          "Outros acionistas - 79,3%",
        ],
      },
      {
        cnpj: "33.000.167/0001-01",
        razaoSocial: "PETRÓLEO BRASILEIRO S.A. - PETROBRAS",
        nomeFantasia: "Petrobras",
        porte: "GRANDE",
        capital: "R$ 264.600.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "03/10/1953",
        cnae: "06.00-0/00 - Extração de petróleo e gás natural",
        endereco: "Avenida República do Chile, 65 - Rio de Janeiro/RJ",
        telefone: "(21) 3224-1510",
        socios: ["União Federal - 50,26%", "Outros acionistas - 49,74%"],
      },
      {
        cnpj: "02.558.157/0001-62",
        razaoSocial: "BANCO DO BRASIL S.A.",
        nomeFantasia: "Banco do Brasil",
        porte: "GRANDE",
        capital: "R$ 36.300.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "12/10/1808",
        cnae: "64.22-1/00 - Bancos múltiplos",
        endereco: "SBS Quadra 1, Bloco C - Brasília/DF",
        telefone: "(61) 3493-9002",
        socios: ["Tesouro Nacional - 54,3%", "Outros acionistas - 45,7%"],
      },
      {
        cnpj: "60.746.948/0001-12",
        razaoSocial: "VALE S.A.",
        nomeFantasia: "Vale",
        porte: "GRANDE",
        capital: "R$ 86.800.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "06/06/1942",
        cnae: "07.00-0/00 - Extração de minerais metálicos",
        endereco: "Praia de Botafogo, 186 - Rio de Janeiro/RJ",
        telefone: "(21) 3485-3730",
        socios: [
          "Litel Participações - 33,2%",
          "Bradespar - 17,4%",
          "Outros acionistas - 49,4%",
        ],
      },
      {
        cnpj: "04.728.162/0001-73",
        razaoSocial: "B2W DIGITAL LTDA.",
        nomeFantasia: "Americanas.com",
        porte: "GRANDE",
        capital: "R$ 2.800.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "19/07/2006",
        cnae: "47.81-4/00 - Comércio varejista de artigos do vestuário",
        endereco: "Rua Sacadura Cabral, 102 - Rio de Janeiro/RJ",
        telefone: "(21) 3206-2000",
        socios: ["Lojas Americanas S.A. - 62,1%", "Outros acionistas - 37,9%"],
      },
      {
        cnpj: "07.526.557/0001-00",
        razaoSocial: "NATURA COSMÉTICOS S.A.",
        nomeFantasia: "Natura",
        porte: "GRANDE",
        capital: "R$ 2.550.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "24/08/1974",
        cnae: "20.42-8/00 - Fabricação de produtos de higiene pessoal",
        endereco: "Rua Professor Atílio Innocenti, 165 - São Paulo/SP",
        telefone: "(11) 4446-3000",
        socios: [
          "Guilherme Peirao Leal - 12,8%",
          "Pedro Luiz Barreiros Passos - 12,8%",
          "Outros acionistas - 74,4%",
        ],
      },
      {
        cnpj: "00.360.305/0001-04",
        razaoSocial: "BANCO BRADESCO S.A.",
        nomeFantasia: "Bradesco",
        porte: "GRANDE",
        capital: "R$ 21.600.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "10/03/1943",
        cnae: "64.22-1/00 - Bancos múltiplos",
        endereco: "Cidade de Deus, s/n - Osasco/SP",
        telefone: "(11) 2194-0922",
        socios: [
          "Cidade de Deus Participações - 35,2%",
          "Outros acionistas - 64,8%",
        ],
      },
      {
        cnpj: "61.532.644/0001-15",
        razaoSocial: "ITAÚ UNIBANCO HOLDING S.A.",
        nomeFantasia: "Itaú Unibanco",
        porte: "GRANDE",
        capital: "R$ 62.800.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "04/02/2008",
        cnae: "64.11-2/00 - Banco central",
        endereco: "Praça Alfredo Egydio de Souza Aranha, 100 - São Paulo/SP",
        telefone: "(11) 5019-1111",
        socios: ["Itaúsa S.A. - 36,7%", "Outros acionistas - 63,3%"],
      },
      {
        cnpj: "14.200.166/0001-56",
        razaoSocial: "JBS S.A.",
        nomeFantasia: "JBS",
        porte: "GRANDE",
        capital: "R$ 8.800.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "31/03/1953",
        cnae: "10.12-1/00 - Abate de suínos, aves e outros pequenos animais",
        endereco: "Avenida Marginal Direita do Tietê, 500 - São Paulo/SP",
        telefone: "(11) 3144-4000",
        socios: ["J&F Participações - 42,3%", "Outros acionistas - 57,7%"],
      },
      {
        cnpj: "59.285.411/0001-13",
        razaoSocial: "EMPRESA BRASILEIRA DE CORREIOS E TELÉGRAFOS",
        nomeFantasia: "Correios",
        porte: "GRANDE",
        capital: "R$ 2.500.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "20/03/1969",
        cnae: "53.10-5/00 - Atividades do Correio Nacional",
        endereco: "SBN Quadra 1, Bloco A - Brasília/DF",
        telefone: "(61) 3003-0100",
        socios: ["União Federal - 100%"],
      },
      {
        cnpj: "17.329.076/0001-81",
        razaoSocial: "COMPANHIA ENERGÉTICA DE MINAS GERAIS - CEMIG",
        nomeFantasia: "CEMIG",
        porte: "GRANDE",
        capital: "R$ 7.200.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "22/05/1952",
        cnae: "35.11-5/00 - Geração de energia elétrica",
        endereco: "Avenida Barbacena, 1200 - Belo Horizonte/MG",
        telefone: "(31) 3506-5024",
        socios: ["Estado de Minas Gerais - 51%", "Outros acionistas - 49%"],
      },
      {
        cnpj: "73.178.600/0001-04",
        razaoSocial: "WEG S.A.",
        nomeFantasia: "WEG",
        porte: "GRANDE",
        capital: "R$ 9.500.000.000,00",
        situacao: "ATIVA",
        dataAbertura: "16/09/1961",
        cnae: "27.10-4/00 - Fabricação de motores elétricos",
        endereco: "Avenida Prefeito Waldemar Grubba, 3300 - Jaraguá do Sul/SC",
        telefone: "(47) 3276-4000",
        socios: ["WEG Participações - 33,5%", "Outros acionistas - 66,5%"],
      },
    ];

    // Buscar empresa específica baseada no CNPJ ou nome
    let empresa = null;

    // Primeiro, tentar encontrar pelo CNPJ exato
    const cnpjRegex = /(\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2})/;
    const cnpjMatch = searchTerm.match(cnpjRegex);

    if (cnpjMatch) {
      // Normalizar CNPJ removendo formatação
      const cnpjPesquisado = cnpjMatch[1].replace(/[^\d]/g, "");
      empresa = empresas.find(
        (emp) => emp.cnpj.replace(/[^\d]/g, "") === cnpjPesquisado
      );
    }

    // Se não encontrou pelo CNPJ, buscar pelo nome da empresa
    if (!empresa) {
      const searchLower = searchTerm.toLowerCase();
      empresa = empresas.find(
        (emp) =>
          emp.nomeFantasia.toLowerCase().includes(searchLower) ||
          emp.razaoSocial.toLowerCase().includes(searchLower) ||
          searchLower.includes(emp.nomeFantasia.toLowerCase()) ||
          searchLower.includes(
            emp.razaoSocial.toLowerCase().split(" ")[0].toLowerCase()
          )
      );
    }

    // Se ainda não encontrou, usar a primeira empresa como fallback
    if (!empresa) {
      empresa = empresas[0];
    }

    return [
      {
        id: 9,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "CNPJ",
        value: empresa.cnpj,
        confidence: 99,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 10,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Razão Social",
        value: empresa.razaoSocial,
        confidence: 99,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 11,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Nome Fantasia",
        value: empresa.nomeFantasia,
        confidence: 99,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 12,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Situação Cadastral",
        value: `${empresa.situacao} desde ${empresa.dataAbertura}`,
        confidence: 99,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 13,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Porte da Empresa",
        value: empresa.porte,
        confidence: 99,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 14,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Capital Social",
        value: empresa.capital,
        confidence: 95,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 15,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "CNAE Principal",
        value: empresa.cnae,
        confidence: 99,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 16,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Endereço",
        value: empresa.endereco,
        confidence: 92,
        lastUpdate: "2023-11-10T16:30:00Z",
        verified: true,
      },
      {
        id: 17,
        category: "Dados Empresariais",
        source: "Junta Comercial",
        field: "Sócios Principais",
        value: empresa.socios.join(", "),
        confidence: 95,
        lastUpdate: "2023-11-10T16:30:00Z",
        verified: true,
      },
      {
        id: 18,
        category: "Dados Empresariais",
        source: "Receita Federal",
        field: "Telefone",
        value: empresa.telefone,
        confidence: 87,
        lastUpdate: "2023-08-15T11:30:00Z",
        verified: true,
      },
      {
        id: 19,
        category: "Dados Financeiros",
        source: "SERASA",
        field: "Score Empresarial",
        value: "950 pontos - Excelente",
        confidence: 88,
        lastUpdate: "2024-01-15T10:30:00Z",
        verified: false,
      },
      {
        id: 20,
        category: "Dados Financeiros",
        source: "Banco Central",
        field: "Situação no SCR",
        value: "Sem restrições cadastrais",
        confidence: 92,
        lastUpdate: "2024-01-10T14:20:00Z",
        verified: true,
      },
      {
        id: 21,
        category: "Dados Empresariais",
        source: "Junta Comercial",
        field: "Atividade Econômica",
        value: empresa.cnae.split(" - ")[1],
        confidence: 98,
        lastUpdate: "2024-01-20T14:00:00Z",
        verified: true,
      },
      {
        id: 22,
        category: "Dados Financeiros",
        source: "SERASA",
        field: "Faturamento Estimado",
        value:
          empresa.porte === "GRANDE"
            ? "Acima de R$ 300.000.000,00 anuais"
            : "Entre R$ 4.800.000,00 e R$ 300.000.000,00 anuais",
        confidence: 78,
        lastUpdate: "2023-12-01T12:00:00Z",
        verified: false,
      },
    ];
  }

  // Resultados gerais para CPF/nome
  return [
    {
      id: 13,
      category: "Dados Pessoais",
      source: "Receita Federal",
      field: "Nome Completo",
      value: "João Silva Santos",
      confidence: 98,
      lastUpdate: "2024-01-15T10:30:00Z",
      verified: true,
    },
    {
      id: 14,
      category: "Dados Pessoais",
      source: "TSE",
      field: "Data de Nascimento",
      value: "15/03/1985 (38 anos)",
      confidence: 95,
      lastUpdate: "2024-01-10T14:20:00Z",
      verified: true,
    },
    {
      id: 15,
      category: "Dados Pessoais",
      source: "IBGE",
      field: "Endereço Residencial",
      value: "Rua das Flores, 123 - Vila Madalena - São Paulo/SP",
      confidence: 89,
      lastUpdate: "2023-08-15T11:30:00Z",
      verified: true,
    },
    {
      id: 16,
      category: "Dados Financeiros",
      source: "SERASA",
      field: "Score de Crédito",
      value: "750 pontos - Baixo Risco",
      confidence: 87,
      lastUpdate: "2024-01-20T08:00:00Z",
      verified: false,
    },
    {
      id: 17,
      category: "Redes Sociais",
      source: "LinkedIn",
      field: "Perfil Profissional",
      value: "Analista de Sistemas Sênior na TechCorp - 500+ conexões",
      confidence: 82,
      lastUpdate: "2024-01-18T12:00:00Z",
      verified: false,
    },
    {
      id: 18,
      category: "Propriedades",
      source: "Cartório de Imóveis",
      field: "Apartamento Residencial",
      value: "Apartamento 45m² - Rua das Flores, 123 - Valor: R$ 450.000",
      confidence: 94,
      lastUpdate: "2023-08-15T11:30:00Z",
      verified: true,
    },
    {
      id: 19,
      category: "Dados Familiares",
      source: "Cartório Civil",
      field: "Estado Civil",
      value: "Casado com Maria Santos Silva desde 10/06/2015",
      confidence: 93,
      lastUpdate: "2022-06-10T10:00:00Z",
      verified: true,
    },
    {
      id: 20,
      category: "Dados Acadêmicos",
      source: "MEC",
      field: "Formação Superior",
      value: "Bacharel em Ciência da Computação - USP (2003-2007)",
      confidence: 88,
      lastUpdate: "2023-03-20T09:45:00Z",
      verified: true,
    },
  ];
};

// Função para calcular estatísticas por categoria
export const getCategoryStats = (results) => {
  const categories = {};

  results.forEach((result) => {
    if (!categories[result.category]) {
      categories[result.category] = {
        count: 0,
        totalConfidence: 0,
        verified: 0,
      };
    }
    categories[result.category].count++;
    categories[result.category].totalConfidence += result.confidence;
    if (result.verified) {
      categories[result.category].verified++;
    }
  });

  // Calcular médias
  Object.keys(categories).forEach((cat) => {
    categories[cat].avgConfidence = Math.round(
      categories[cat].totalConfidence / categories[cat].count
    );
  });

  return categories;
};

// Dados adicionais para relatórios
export const getSearchMetrics = () => {
  return {
    totalSearches: 15420,
    successRate: 94.2,
    avgResponseTime: 1.8,
    topCategories: [
      { name: "Dados Pessoais", count: 5240 },
      { name: "Violações de Trânsito", count: 3180 },
      { name: "Dados Empresariais", count: 2890 },
      { name: "Processos Judiciais", count: 2110 },
      { name: "Propriedades", count: 1560 },
      { name: "Dados Financeiros", count: 440 },
    ],
  };
};
